/**
 * Followup nudge generator.
 *
 * Fires when a recipient got the initial DM 4+ hours ago AND hasn't
 * clicked the CTA link. Sends a short, casual "did you get a chance to
 * check it?" message in the creator's voice.
 *
 * Generated by Claude with strict guardrails — NEVER pushy, NEVER asks
 * for the sale, just a gentle reminder. Pushy nudges kill brand trust
 * and trip Meta's spam ML.
 *
 * Falls back to a templated nudge if Anthropic call fails or is unset.
 */

import Anthropic from '@anthropic-ai/sdk';

const SYSTEM = `You write very short Instagram DM reminder messages. The message will have a LINK appended after it on a new line — your job is to write only the lead-in sentence.

Constraints:
- 1 sentence MAX. Conversational, casual, like a friend bumping a message.
- Phrase it as a soft re-send: "here it is again", "bumping this", "wanted to make sure you got this", "the link from earlier in case it got buried".
- DO NOT include any URL — the link is appended automatically.
- NEVER pushy. Never "act now", "don't miss out", "limited time", "buy now". No exclamation marks.
- Match the voice of the creator from the samples provided.
- If the creator's voice uses emojis, use ONE (max). Otherwise none.
- Output ONLY the message text — no quotes, no preamble, no link.`;

export async function generateFollowupNudge(input: {
  tenantUsername: string;
  voiceSamples: string[];      // creator's past DM bodies (max 6)
  originalDmText: string;      // what we sent originally
}): Promise<string> {
  const fallback = `hey {{username}} — bumping the link from earlier in case you missed it`;
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) return fallback;

  try {
    const claude = new Anthropic({ apiKey });
    const prompt = `Creator: @${input.tenantUsername}

Creator's voice samples:
${input.voiceSamples.slice(0, 6).map((s, i) => `${i + 1}. "${s.slice(0, 200)}"`).join('\n') || '(no samples — use a neutral casual tone)'}

Original DM that was sent ~4 hours ago to the recipient (use {{username}} placeholder for their handle):
"${input.originalDmText.slice(0, 300)}"

Write a 1-sentence lead-in for re-sending the same link. The URL will be appended automatically after your message on a new line — DO NOT include any URL or "here:" in your output.`;

    const res = await claude.messages.create({
      model: 'claude-opus-4-5',
      max_tokens: 120,
      system: SYSTEM,
      messages: [{ role: 'user', content: prompt }],
    });
    const block = res.content[0];
    const text = block.type === 'text' ? block.text.trim() : '';
    if (!text || text.length > 280) return fallback;
    // Ensure {{username}} placeholder so we can substitute the recipient handle later
    return text.includes('{{') ? text : text.replace(/^(hey|hi|hii|yo)\b\s*/i, (m) => `${m} {{username}} `);
  } catch {
    return fallback;
  }
}
