// StackPicks Connect — App Directory catalog.
//
// 500+ apps that we expose through the unified `@stackpicks/mcp` gateway.
// Each app's tools become available to Claude / Cursor / OpenAI agents once
// the user OAuths through StackPicks Connect.
//
// Status flags:
//   - 'live'  — OAuth ready, tools exposed via @stackpicks/mcp
//   - 'beta'  — OAuth working, partial tool coverage
//   - 'soon'  — Coming next; user can request priority (waitlist)
//
// We launch MVP with 6 'live' providers (GitHub, Gmail, Slack, Notion,
// Discord, Google Drive). The rest are 'soon' so users can browse the full
// 500+ catalog from day one, even before all OAuth wires in. This matches
// how Composio and Pipedream list their full catalog at launch.

export type ConnectCategory =
  | 'dev-code'
  | 'email'
  | 'messaging'
  | 'productivity'
  | 'project-mgmt'
  | 'crm-sales'
  | 'marketing'
  | 'social'
  | 'support'
  | 'analytics'
  | 'database'
  | 'vector-ai'
  | 'ai-ml'
  | 'payments'
  | 'ecommerce'
  | 'hr-recruit'
  | 'finance'
  | 'design'
  | 'scheduling'
  | 'forms'
  | 'storage-cloud'
  | 'auth-identity'
  | 'devtools'
  | 'media'
  | 'misc';

export interface CategoryMeta {
  slug: ConnectCategory;
  name: string;
  icon: string;
  blurb: string;
}

export const CONNECT_CATEGORIES: CategoryMeta[] = [
  { slug: 'dev-code',       name: 'Dev & Code',        icon: 'code',          blurb: 'Git, CI, deploy, containers' },
  { slug: 'email',          name: 'Email',             icon: 'mail',          blurb: 'Inbox + transactional' },
  { slug: 'messaging',      name: 'Messaging & Chat',  icon: 'message-circle',blurb: 'Slack, Discord, Teams' },
  { slug: 'productivity',   name: 'Productivity',      icon: 'check-square',  blurb: 'Notes, docs, sheets' },
  { slug: 'project-mgmt',   name: 'Project Mgmt',      icon: 'kanban',        blurb: 'Linear, Jira, Asana' },
  { slug: 'crm-sales',      name: 'CRM & Sales',       icon: 'briefcase',     blurb: 'Pipelines, outreach' },
  { slug: 'marketing',      name: 'Marketing',         icon: 'megaphone',     blurb: 'Newsletters, campaigns' },
  { slug: 'social',         name: 'Social Media',      icon: 'share-2',       blurb: 'X, LinkedIn, IG, TikTok' },
  { slug: 'support',        name: 'Customer Support',  icon: 'life-buoy',     blurb: 'Helpdesk, live chat' },
  { slug: 'analytics',      name: 'Analytics',         icon: 'bar-chart-3',   blurb: 'Product + web analytics' },
  { slug: 'database',       name: 'Databases',         icon: 'database',      blurb: 'SQL, NoSQL, time-series' },
  { slug: 'vector-ai',      name: 'Vector DBs',        icon: 'layers',        blurb: 'RAG-ready stores' },
  { slug: 'ai-ml',          name: 'AI & ML',           icon: 'sparkles',      blurb: 'LLMs, voice, vision' },
  { slug: 'payments',       name: 'Payments',          icon: 'credit-card',   blurb: 'Stripe, Razorpay, etc.' },
  { slug: 'ecommerce',      name: 'E-commerce',        icon: 'shopping-bag',  blurb: 'Storefronts + marketplaces' },
  { slug: 'hr-recruit',     name: 'HR & Recruiting',   icon: 'users',         blurb: 'ATS, payroll, hiring' },
  { slug: 'finance',        name: 'Finance & Books',   icon: 'wallet',        blurb: 'Accounting, banking' },
  { slug: 'design',         name: 'Design',            icon: 'palette',       blurb: 'Figma, Canva, Framer' },
  { slug: 'scheduling',     name: 'Scheduling',        icon: 'calendar',      blurb: 'Calendly, Cal.com, Acuity' },
  { slug: 'forms',          name: 'Forms & Surveys',   icon: 'clipboard-list',blurb: 'Typeform, Tally, Jotform' },
  { slug: 'storage-cloud',  name: 'Cloud & Storage',   icon: 'cloud',         blurb: 'AWS, GCP, Azure, R2' },
  { slug: 'auth-identity',  name: 'Auth & Identity',   icon: 'shield',        blurb: 'Clerk, Auth0, WorkOS' },
  { slug: 'devtools',       name: 'DevTools',          icon: 'wrench',        blurb: 'APIs, monitoring, security' },
  { slug: 'media',          name: 'Media & Video',     icon: 'video',         blurb: 'YouTube, Vimeo, Loom' },
  { slug: 'misc',           name: 'Other',             icon: 'grid',          blurb: 'Everything else' },
];

export interface ConnectApp {
  slug: string;                 // url-safe id; matches Nango provider config
  name: string;                 // display name
  category: ConnectCategory;
  status: 'live' | 'beta' | 'soon';
  tagline: string;              // ≤ 60 chars — shown on card
  popular?: boolean;            // surface in "Most popular" rail
  toolCount?: number;           // approx tools exposed once connected
  scopes?: string;              // human-readable scope hint shown pre-OAuth
  color?: string;               // tailwind class for accent stripe
}

// Compact builder — keeps the file small. Each tuple becomes a full ConnectApp.
type T = [slug: string, name: string, tagline: string, opts?: Partial<Omit<ConnectApp, 'slug' | 'name' | 'tagline' | 'category'>>];

function group(category: ConnectCategory, items: T[]): ConnectApp[] {
  return items.map(([slug, name, tagline, opts]) => ({
    slug, name, tagline, category,
    status: 'soon',
    ...opts,
  }));
}

// ---- Providers. Only flip to 'live' once BOTH are true:
//        1. A Nango integration exists for the slug (in the prod env)
//        2. core/connect/executors has a handler for it
//      GitHub is fully wired. The rest stay 'soon' until each is added to
//      Nango + given an executor — flipping prematurely shows users a real
//      "Integration does not exist" error from Nango.
const LIVE: ConnectApp[] = [
  { slug: 'github',        name: 'GitHub',        category: 'dev-code',    status: 'live', popular: true, toolCount: 18, scopes: 'Repos, PRs, issues, actions', tagline: 'Code hosting + PRs + issues',         color: 'from-zinc-500/40 to-zinc-700/40' },
  { slug: 'gmail',         name: 'Gmail',         category: 'email',       status: 'soon', popular: true, toolCount: 9,  scopes: 'Read, search, send drafts',  tagline: 'Send, search, draft emails',          color: 'from-red-500/40 to-orange-500/40' },
  { slug: 'slack',         name: 'Slack',         category: 'messaging',   status: 'live', popular: true, toolCount: 5, scopes: 'Channels, history, post, users',tagline: 'Post, read & summarize channels',    color: 'from-purple-500/40 to-pink-500/40' },
  { slug: 'notion',        name: 'Notion',        category: 'productivity',status: 'live', popular: true, toolCount: 5, scopes: 'Read + write pages, DBs',    tagline: 'Read + write pages and databases',    color: 'from-zinc-300/40 to-zinc-500/40' },
  { slug: 'discord',       name: 'Discord',       category: 'messaging',   status: 'soon', popular: true, toolCount: 10, scopes: 'Guilds, channels, messages', tagline: 'Bot messages + role mgmt',            color: 'from-indigo-500/40 to-violet-500/40' },
  { slug: 'google-drive',  name: 'Google Drive',  category: 'storage-cloud',status: 'soon',popular: true, toolCount: 12, scopes: 'Files, folders, comments',   tagline: 'Files, folders, upload, search',      color: 'from-yellow-400/40 to-green-500/40' },
];

// ---- Catalog (status: soon — flips to live as we wire each provider) ------
const CATALOG: ConnectApp[] = [
  ...group('dev-code', [
    ['gitlab',          'GitLab',           'Self-hosted git + CI'],
    ['bitbucket',       'Bitbucket',        'Atlassian git + Pipelines'],
    ['azure-devops',    'Azure DevOps',     'Microsoft repos + boards'],
    ['gitea',           'Gitea',            'Lightweight self-hosted git'],
    ['vercel',          'Vercel',           'Deploys, projects, envs',         { popular: true, toolCount: 9 }],
    ['netlify',         'Netlify',          'Sites, deploys, functions'],
    ['railway',         'Railway',          'Services, deploys, envs'],
    ['render',          'Render',           'Web services + workers'],
    ['fly-io',          'Fly.io',           'Edge containers'],
    ['heroku',          'Heroku',           'Apps + dynos + addons'],
    ['cloudflare',      'Cloudflare',       'DNS, Workers, R2, KV',            { popular: true }],
    ['circleci',        'CircleCI',         'Pipelines + builds'],
    ['github-actions',  'GitHub Actions',   'Workflow runs + secrets'],
    ['jenkins',         'Jenkins',          'Self-hosted CI'],
    ['travis-ci',       'Travis CI',        'Hosted CI'],
    ['drone',           'Drone',            'Container-native CI'],
    ['buildkite',       'Buildkite',        'Hybrid CI/CD'],
    ['codecov',         'Codecov',          'Coverage reports'],
    ['sentry',          'Sentry',           'Error tracking + perf',           { popular: true }],
    ['datadog',         'Datadog',          'APM, logs, metrics'],
    ['new-relic',       'New Relic',        'Full-stack observability'],
    ['honeycomb',       'Honeycomb',        'Observability + tracing'],
    ['logrocket',       'LogRocket',        'Session replay'],
    ['rollbar',         'Rollbar',          'Real-time error tracking'],
    ['bugsnag',         'Bugsnag',          'Stability monitoring'],
    ['pagerduty',       'PagerDuty',        'On-call + alerting'],
    ['opsgenie',        'Opsgenie',         'Incident response'],
    ['statuspage',      'Statuspage',       'Public status pages'],
    ['betterstack',     'BetterStack',      'Uptime + logs + status'],
    ['uptimerobot',     'UptimeRobot',      'Uptime monitoring'],
    ['pingdom',         'Pingdom',          'Synthetic uptime'],
    ['replit',          'Replit',           'Cloud IDE + repls'],
    ['codesandbox',     'CodeSandbox',      'Sandbox dev'],
    ['stackblitz',      'StackBlitz',       'WebContainer dev'],
    ['gitpod',          'Gitpod',           'Cloud dev environments'],
    ['github-codespaces','Codespaces',      'GitHub cloud dev'],
    ['snyk',            'Snyk',             'Vulnerability scanning'],
    ['socket',          'Socket',           'Supply-chain security'],
    ['dependabot',      'Dependabot',       'Dep updates'],
    ['renovate',        'Renovate',         'Auto dep PRs'],
    ['sonarqube',       'SonarQube',        'Code quality + security'],
  ]),
  ...group('email', [
    ['outlook',         'Outlook',          'Microsoft email + calendar',      { popular: true, toolCount: 11 }],
    ['yahoo-mail',      'Yahoo Mail',       'Inbox + send'],
    ['protonmail',      'ProtonMail',       'Encrypted email'],
    ['icloud-mail',     'iCloud Mail',      'Apple mail'],
    ['fastmail',        'Fastmail',         'Privacy-first inbox'],
    ['hey',             'HEY',              'Inbox by 37signals'],
    ['zoho-mail',       'Zoho Mail',        'Business email'],
    ['mailgun',         'Mailgun',          'Transactional SMTP'],
    ['sendgrid',        'SendGrid',         'Transactional + marketing',       { popular: true }],
    ['postmark',        'Postmark',         'Transactional email'],
    ['resend',          'Resend',           'Developer-first email',           { popular: true }],
    ['mailjet',         'Mailjet',          'Transactional + bulk'],
    ['amazon-ses',      'Amazon SES',       'AWS email service'],
    ['sparkpost',       'SparkPost',        'Email API'],
    ['mailtrap',        'Mailtrap',         'Email testing + send'],
    ['brevo',           'Brevo',            'Email + SMS + CRM'],
    ['mailerlite',      'MailerLite',       'Email marketing'],
    ['mailchimp',       'Mailchimp',        'Email + audiences',               { popular: true }],
    ['constant-contact','Constant Contact', 'SMB email marketing'],
    ['aweber',          'AWeber',           'Newsletters + automation'],
    ['getresponse',     'GetResponse',      'Marketing + webinars'],
    ['convertkit',      'ConvertKit',       'Creator email'],
    ['kit',             'Kit (ConvertKit)', 'Newsletter platform'],
    ['activecampaign',  'ActiveCampaign',   'CRM + automation'],
    ['drip',            'Drip',             'Ecom CRM email'],
    ['klaviyo',         'Klaviyo',          'Ecom email + SMS',                { popular: true }],
    ['customer-io',     'Customer.io',      'Behavior-based messaging'],
    ['iterable',        'Iterable',         'Cross-channel marketing'],
    ['braze',           'Braze',            'Customer engagement'],
    ['beehiiv',         'Beehiiv',          'Newsletters + monetization'],
    ['substack',        'Substack',         'Paid newsletters'],
    ['buttondown',      'Buttondown',       'Markdown newsletters'],
    ['ghost',           'Ghost',            'Publishing platform'],
  ]),
  ...group('messaging', [
    ['microsoft-teams', 'Microsoft Teams',  'Channels, chats, meetings',       { popular: true }],
    ['telegram',        'Telegram',         'Bots, channels, DMs'],
    ['whatsapp',        'WhatsApp Business','Bulk msgs + customer ops',        { popular: true }],
    ['signal',          'Signal',           'Encrypted DMs'],
    ['webex',           'Cisco Webex',      'Enterprise meet + chat'],
    ['mattermost',      'Mattermost',       'Self-hosted Slack alt'],
    ['rocketchat',      'Rocket.Chat',      'Self-hosted team chat'],
    ['zulip',           'Zulip',            'Threaded team chat'],
    ['element',         'Element (Matrix)', 'Decentralized chat'],
    ['twist',           'Twist',            'Async team comms'],
    ['flock',           'Flock',            'Team messaging'],
    ['groupme',         'GroupMe',          'Group SMS'],
    ['kik',             'Kik',              'Bot-first messaging'],
    ['line',            'LINE',             'Asia-popular messenger'],
    ['wechat',          'WeChat',           'China super-app'],
    ['viber',           'Viber',            'Voice + msg'],
    ['twilio',          'Twilio',           'SMS, voice, WhatsApp API',        { popular: true }],
    ['messagebird',     'MessageBird',      'SMS + voice + email'],
    ['plivo',           'Plivo',            'CPaaS SMS + voice'],
    ['vonage',          'Vonage',           'Comms APIs'],
    ['textmagic',       'TextMagic',        'Business SMS'],
  ]),
  ...group('productivity', [
    ['google-docs',     'Google Docs',      'Docs read + write',               { popular: true, toolCount: 8 }],
    ['google-sheets',   'Google Sheets',    'Read + write spreadsheets',       { popular: true, toolCount: 10 }],
    ['google-slides',   'Google Slides',    'Presentations'],
    ['google-calendar', 'Google Calendar',  'Events + invites',                { popular: true }],
    ['google-keep',     'Google Keep',      'Notes + reminders'],
    ['microsoft-word',  'Microsoft Word',   'Docs'],
    ['microsoft-excel', 'Microsoft Excel',  'Spreadsheets'],
    ['microsoft-powerpoint','PowerPoint',   'Slides'],
    ['onenote',         'OneNote',          'MS notes'],
    ['outlook-calendar','Outlook Calendar', 'MS calendar'],
    ['coda',            'Coda',             'Docs + DB hybrid'],
    ['airtable',        'Airtable',         'Spreadsheet-DB',                  { popular: true }],
    ['baserow',         'Baserow',          'Open-source Airtable'],
    ['nocodb',          'NocoDB',           'OSS Airtable on Postgres'],
    ['smartsheet',      'Smartsheet',       'Work mgmt sheets'],
    ['confluence',      'Confluence',       'Atlassian wiki'],
    ['evernote',        'Evernote',         'Notes + clip web'],
    ['onenote-microsoft','Microsoft OneNote','MS notebooks'],
    ['obsidian',        'Obsidian',         'Local markdown notes',            { popular: true }],
    ['logseq',          'Logseq',           'Outliner + graph'],
    ['roam-research',   'Roam Research',    'Networked thought'],
    ['remnote',         'RemNote',          'Notes + spaced rep'],
    ['anytype',         'Anytype',          'Local-first OS'],
    ['standard-notes',  'Standard Notes',   'Encrypted notes'],
    ['joplin',          'Joplin',           'OSS Evernote alt'],
    ['bear',            'Bear',             'Apple markdown notes'],
    ['apple-notes',     'Apple Notes',      'iCloud notes'],
    ['reflect',         'Reflect',          'Networked daily notes'],
    ['craft',           'Craft Docs',       'Beautiful docs'],
    ['mem',             'Mem.ai',           'AI-native notes'],
    ['workflowy',       'WorkFlowy',        'Outliner'],
    ['dynalist',        'Dynalist',         'Outliner alt'],
  ]),
  ...group('project-mgmt', [
    ['linear',          'Linear',           'Issue tracker + cycles',          { popular: true, toolCount: 5, status: 'live' }],
    ['jira',            'Jira',             'Atlassian issues + sprints',      { popular: true, toolCount: 16 }],
    ['asana',           'Asana',            'Tasks + projects',                { popular: true }],
    ['trello',          'Trello',           'Kanban boards'],
    ['clickup',         'ClickUp',          'Everything-app for work'],
    ['monday',          'Monday.com',       'Work OS'],
    ['basecamp',        'Basecamp',         'Calm PM'],
    ['height',          'Height',           'AI-native PM'],
    ['shortcut',        'Shortcut',         'Engineering issues'],
    ['pivotal-tracker', 'Pivotal Tracker',  'Agile PM'],
    ['wrike',           'Wrike',            'Enterprise PM'],
    ['teamwork',        'Teamwork',         'Client work PM'],
    ['todoist',         'Todoist',          'Task list',                       { popular: true }],
    ['ticktick',        'TickTick',         'Tasks + habits'],
    ['things-3',        'Things 3',         'Cultured Code tasks'],
    ['omnifocus',       'OmniFocus',        'GTD app'],
    ['microsoft-todo',  'Microsoft To Do',  'MS tasks'],
    ['any-do',          'Any.do',           'Tasks + calendar'],
    ['plaky',           'Plaky',            'Free PM'],
    ['kitemaker',       'Kitemaker',        'Product PM'],
    ['productive',      'Productive',       'Agency PM + finance'],
    ['float',           'Float',            'Resource scheduling'],
    ['resource-guru',   'Resource Guru',    'Team scheduling'],
    ['toggl-plan',      'Toggl Plan',       'Timeline PM'],
  ]),
  ...group('crm-sales', [
    ['hubspot',         'HubSpot',          'CRM + marketing + sales',         { popular: true, toolCount: 22 }],
    ['salesforce',      'Salesforce',       'Enterprise CRM',                  { popular: true, toolCount: 25 }],
    ['pipedrive',       'Pipedrive',        'Sales pipeline CRM',              { popular: true }],
    ['zoho-crm',        'Zoho CRM',         'SMB CRM'],
    ['freshsales',      'Freshsales',       'Freshworks CRM'],
    ['close',           'Close',            'Inside sales CRM'],
    ['copper',          'Copper',           'Google Workspace CRM'],
    ['insightly',       'Insightly',        'CRM + PM'],
    ['nutshell',        'Nutshell',         'Sales CRM'],
    ['streak',          'Streak',           'Gmail CRM'],
    ['capsule-crm',     'Capsule CRM',      'Simple CRM'],
    ['attio',           'Attio',            'Modern CRM'],
    ['folk',            'Folk',             'Relationship CRM'],
    ['salesflare',      'Salesflare',       'Auto CRM'],
    ['apollo',          'Apollo.io',        'Prospecting + outreach',          { popular: true }],
    ['outreach',        'Outreach',         'Sales engagement'],
    ['salesloft',       'Salesloft',        'Revenue orchestration'],
    ['reply-io',        'Reply.io',         'Multi-channel outreach'],
    ['lemlist',         'Lemlist',          'Cold email + warmup'],
    ['instantly',       'Instantly',        'Cold email at scale'],
    ['smartlead',       'Smartlead',        'Cold email infra'],
    ['mixmax',          'Mixmax',           'Gmail sales'],
    ['yesware',         'Yesware',          'Email tracking'],
    ['hunter',          'Hunter.io',        'Email finder'],
    ['snov-io',         'Snov.io',          'Lead gen + email'],
    ['lusha',           'Lusha',            'Contact intel'],
    ['zoominfo',        'ZoomInfo',         'B2B data'],
    ['clearbit',        'Clearbit',         'Lead enrichment'],
    ['cognism',         'Cognism',          'B2B prospecting'],
    ['rocketreach',     'RocketReach',      'Contact finder'],
  ]),
  ...group('marketing', [
    ['buffer',          'Buffer',           'Social scheduling',               { popular: true }],
    ['hootsuite',       'Hootsuite',        'Social mgmt'],
    ['later',           'Later',            'IG-first scheduling'],
    ['sprout-social',   'Sprout Social',    'Enterprise social'],
    ['planoly',         'Planoly',          'Visual planner'],
    ['socialbee',       'SocialBee',        'Category-based posting'],
    ['contentstudio',   'ContentStudio',    'Content + social'],
    ['agorapulse',      'Agorapulse',       'Social inbox + sched'],
    ['meetedgar',       'MeetEdgar',        'Evergreen reposting'],
    ['loomly',          'Loomly',           'Calendar + brand'],
    ['typefully',       'Typefully',        'Twitter/X composer'],
    ['tweet-hunter',    'Tweet Hunter',     'X growth + sched'],
    ['hypefury',        'Hypefury',         'X automation'],
    ['publer',          'Publer',           'AI social posts'],
    ['ahrefs',          'Ahrefs',           'SEO toolkit',                     { popular: true }],
    ['semrush',         'Semrush',          'SEO + marketing'],
    ['moz',             'Moz',              'SEO software'],
    ['ubersuggest',     'Ubersuggest',      'Neil Patel SEO'],
    ['screaming-frog',  'Screaming Frog',   'SEO crawler'],
    ['search-console',  'Google Search Console','GSC data',                    { popular: true }],
    ['bing-webmaster',  'Bing Webmaster',   'Bing search data'],
    ['rank-math',       'Rank Math',        'WP SEO'],
    ['surfer',          'Surfer SEO',       'Content optimization'],
    ['indexnow',        'IndexNow',         'Instant search indexing'],
  ]),
  ...group('social', [
    ['twitter-x',       'X (Twitter)',      'Post, search, DMs, threads',      { popular: true, toolCount: 12 }],
    ['linkedin',        'LinkedIn',         'Posts + messages',                { popular: true, toolCount: 10 }],
    ['facebook',        'Facebook',         'Pages + posts'],
    ['instagram',       'Instagram',        'Posts + reels + DMs',             { popular: true }],
    ['tiktok',          'TikTok',           'Video upload + analytics'],
    ['youtube',         'YouTube',          'Videos + comments + analytics',   { popular: true }],
    ['pinterest',       'Pinterest',        'Pins + boards'],
    ['reddit',          'Reddit',           'Posts + comments + DMs',          { popular: true }],
    ['threads',         'Threads',          'Meta micro-blog'],
    ['mastodon',        'Mastodon',         'Fediverse posts'],
    ['bluesky',         'Bluesky',          'AT Protocol social'],
    ['snapchat',        'Snapchat',         'Stories + spotlight'],
    ['tumblr',          'Tumblr',           'Microblog'],
    ['medium',          'Medium',           'Articles'],
    ['dev-to',          'DEV Community',    'Dev articles'],
    ['hashnode',        'Hashnode',         'Dev blogs'],
    ['product-hunt',    'Product Hunt',     'Launch + comments'],
    ['indie-hackers',   'Indie Hackers',    'Founder community'],
    ['hacker-news',     'Hacker News',      'YC news'],
    ['lemmy',           'Lemmy',            'Fediverse Reddit'],
    ['nostr',           'Nostr',            'Protocol social'],
  ]),
  ...group('support', [
    ['intercom',        'Intercom',         'Live chat + helpdesk',            { popular: true, toolCount: 14 }],
    ['zendesk',         'Zendesk',          'Helpdesk + tickets',              { popular: true }],
    ['freshdesk',       'Freshdesk',        'Freshworks support'],
    ['help-scout',      'Help Scout',       'Email-first helpdesk'],
    ['kayako',          'Kayako',           'Helpdesk'],
    ['drift',           'Drift',            'Conversational marketing'],
    ['crisp',           'Crisp',            'Live chat + CRM'],
    ['tawk-to',         'Tawk.to',          'Free live chat'],
    ['livechat',        'LiveChat',         'Live chat platform'],
    ['olark',           'Olark',            'Live chat'],
    ['tidio',           'Tidio',            'Chat + bots'],
    ['gorgias',         'Gorgias',          'Ecom helpdesk'],
    ['front',           'Front',            'Shared inbox'],
    ['missive',         'Missive',          'Team email'],
    ['hiver',           'Hiver',            'Gmail-based helpdesk'],
    ['groove',          'Groove',           'SMB support'],
    ['userback',        'Userback',         'Visual feedback'],
    ['canny',           'Canny',            'Feature requests'],
    ['productboard',    'Productboard',     'Product feedback'],
    ['frill',           'Frill',            'Feedback + roadmap'],
    ['featurebase',     'Featurebase',      'Roadmaps + changelog'],
    ['nolt',            'Nolt',             'Feedback boards'],
    ['fider',           'Fider',            'OSS feedback'],
  ]),
  ...group('analytics', [
    ['google-analytics','Google Analytics', 'GA4 reports',                     { popular: true, toolCount: 12 }],
    ['mixpanel',        'Mixpanel',         'Product analytics',               { popular: true }],
    ['amplitude',       'Amplitude',        'Behavior analytics'],
    ['posthog',         'PostHog',          'OSS product analytics',           { popular: true }],
    ['plausible',       'Plausible',        'Privacy analytics'],
    ['fathom',          'Fathom',           'Simple privacy analytics'],
    ['heap',            'Heap',             'Auto-capture analytics'],
    ['pendo',           'Pendo',            'Product + in-app'],
    ['hotjar',          'Hotjar',           'Heatmaps + replay'],
    ['fullstory',       'FullStory',        'Session replay'],
    ['microsoft-clarity','Microsoft Clarity','Free session replay'],
    ['crazyegg',        'Crazy Egg',        'Heatmaps'],
    ['matomo',          'Matomo',           'OSS Google Analytics'],
    ['umami',           'Umami',            'OSS web analytics'],
    ['simple-analytics','Simple Analytics', 'Privacy stats'],
    ['segment',         'Segment',          'CDP'],
    ['rudderstack',     'RudderStack',      'Warehouse-first CDP'],
    ['snowplow',        'Snowplow',         'OSS event pipeline'],
    ['mparticle',       'mParticle',        'Customer data'],
    ['june',            'June',             'B2B product analytics'],
    ['mode',            'Mode Analytics',   'BI + notebooks'],
    ['metabase',        'Metabase',         'OSS BI'],
    ['superset',        'Apache Superset',  'OSS BI'],
    ['looker',          'Looker',           'Google BI'],
    ['tableau',         'Tableau',          'Enterprise BI'],
    ['power-bi',        'Microsoft Power BI','MS BI'],
    ['hex',             'Hex',              'Data notebooks'],
    ['sigma',           'Sigma',            'Cloud BI'],
    ['preset',          'Preset',           'Hosted Superset'],
    ['redash',          'Redash',           'OSS SQL dashboards'],
  ]),
  ...group('database', [
    ['supabase',        'Supabase',         'Postgres + auth + storage',       { popular: true, toolCount: 14 }],
    ['firebase',        'Firebase',         'Google BaaS',                     { popular: true }],
    ['mongodb',         'MongoDB',          'Document DB',                     { popular: true }],
    ['postgresql',      'PostgreSQL',       'SQL DB'],
    ['mysql',           'MySQL',            'SQL DB'],
    ['mariadb',         'MariaDB',          'MySQL fork'],
    ['sqlite',          'SQLite',           'Embedded SQL'],
    ['redis',           'Redis',            'Cache + KV',                      { popular: true }],
    ['dynamodb',        'DynamoDB',         'AWS NoSQL'],
    ['cosmos-db',       'Azure Cosmos DB',  'MS multi-model'],
    ['bigquery',        'BigQuery',         'Google warehouse',                { popular: true }],
    ['snowflake',       'Snowflake',        'Cloud warehouse'],
    ['databricks',      'Databricks',       'Lakehouse'],
    ['clickhouse',      'ClickHouse',       'OLAP'],
    ['timescaledb',     'TimescaleDB',      'Time-series'],
    ['influxdb',        'InfluxDB',         'Time-series'],
    ['cassandra',       'Cassandra',        'Wide-column'],
    ['scylladb',        'ScyllaDB',         'C++ Cassandra'],
    ['neo4j',           'Neo4j',            'Graph DB'],
    ['arangodb',        'ArangoDB',         'Multi-model'],
    ['faunadb',         'Fauna',            'Serverless DB'],
    ['planetscale',     'PlanetScale',      'Serverless MySQL'],
    ['neon',            'Neon',             'Serverless Postgres'],
    ['xata',            'Xata',             'Serverless DB'],
    ['turso',           'Turso',            'Edge SQLite'],
    ['cockroachdb',     'CockroachDB',      'Distributed SQL'],
    ['yugabytedb',      'YugabyteDB',       'Distributed SQL'],
    ['singlestore',     'SingleStore',      'Real-time SQL'],
    ['surrealdb',       'SurrealDB',        'Multi-model'],
    ['rqlite',          'rqlite',           'Distributed SQLite'],
  ]),
  ...group('vector-ai', [
    ['pinecone',        'Pinecone',         'Managed vector DB',               { popular: true, toolCount: 8 }],
    ['weaviate',        'Weaviate',         'OSS vector + graph'],
    ['qdrant',          'Qdrant',           'Rust vector DB',                  { popular: true }],
    ['chroma',          'Chroma',           'Embeddings DB'],
    ['milvus',          'Milvus',           'OSS scale vectors'],
    ['lancedb',         'LanceDB',          'Embedded vector store'],
    ['vespa',           'Vespa',            'Search + ranking'],
    ['elasticsearch',   'Elasticsearch',    'Search + vectors',                { popular: true }],
    ['opensearch',      'OpenSearch',       'AWS Elastic fork'],
    ['typesense',       'Typesense',        'OSS search'],
    ['meilisearch',     'Meilisearch',      'Instant search'],
    ['algolia',         'Algolia',          'Hosted search'],
    ['marqo',           'Marqo',            'Multi-modal vectors'],
    ['vectara',         'Vectara',          'RAG-as-a-service'],
    ['turbopuffer',     'Turbopuffer',      'Serverless vectors'],
  ]),
  ...group('ai-ml', [
    ['openai',          'OpenAI',           'GPT, DALL·E, Whisper',            { popular: true, toolCount: 11 }],
    ['anthropic',       'Anthropic',        'Claude API',                      { popular: true }],
    ['google-gemini',   'Google Gemini',    'Gemini API'],
    ['cohere',          'Cohere',           'Embed + chat + rerank'],
    ['mistral',         'Mistral',          'OSS + hosted models'],
    ['groq',            'Groq',             'Fast LPU inference'],
    ['together-ai',     'Together AI',      'Hosted OSS models'],
    ['fireworks-ai',    'Fireworks AI',     'Fast OSS inference'],
    ['anyscale',        'Anyscale',         'Ray + OSS LLMs'],
    ['replicate',       'Replicate',        'Run any model',                   { popular: true }],
    ['hugging-face',    'Hugging Face',     'Models + datasets',               { popular: true }],
    ['stability-ai',    'Stability AI',     'SD image gen'],
    ['runway',          'Runway',           'AI video'],
    ['eleven-labs',     'ElevenLabs',       'TTS + voice clone',               { popular: true }],
    ['assemblyai',      'AssemblyAI',       'Speech-to-text'],
    ['deepgram',        'Deepgram',         'STT API'],
    ['whisper-api',     'Whisper',          'OpenAI STT'],
    ['modal',           'Modal',            'Serverless GPU'],
    ['runpod',          'RunPod',           'GPU cloud'],
    ['lambda-labs',     'Lambda Labs',      'GPU cloud'],
    ['banana',          'Banana',           'GPU inference'],
    ['perplexity',      'Perplexity',       'Search-first LLM'],
    ['you-com',         'You.com',          'AI search'],
    ['exa',             'Exa',              'Embeddings search API'],
    ['serper',          'Serper',           'Google search API'],
    ['serpapi',         'SerpApi',          'Search engine API'],
    ['firecrawl',       'Firecrawl',        'Scrape + search the web for LLMs', { status: 'live', toolCount: 3 }],
    ['apify',           'Apify',            'Web scraping platform'],
    ['browserless',     'Browserless',      'Headless browser as a service'],
    ['scrapingbee',     'ScrapingBee',      'Scrape via API'],
    ['langsmith',       'LangSmith',        'LLM observability'],
    ['langfuse',        'Langfuse',         'OSS LLM obs'],
    ['helicone',        'Helicone',         'LLM logging + cache'],
    ['portkey',         'Portkey',          'AI gateway'],
    ['braintrust',      'Braintrust',       'LLM evals'],
    ['humanloop',       'Humanloop',        'LLM dev platform'],
    ['promptlayer',     'PromptLayer',      'Prompt mgmt'],
    ['weights-biases',  'Weights & Biases', 'ML experiments'],
    ['mlflow',          'MLflow',           'OSS ML lifecycle'],
    ['comet',           'Comet',            'ML experiment tracking'],
  ]),
  ...group('payments', [
    ['stripe',          'Stripe',           'Cards + subs + invoices',         { popular: true, toolCount: 18 }],
    ['razorpay',        'Razorpay',         'India payments + payouts',        { popular: true, toolCount: 14 }],
    ['paypal',          'PayPal',           'Global payments'],
    ['square',          'Square',           'POS + payments'],
    ['braintree',       'Braintree',        'PayPal payments'],
    ['adyen',           'Adyen',            'Enterprise payments'],
    ['mollie',          'Mollie',           'EU payments'],
    ['klarna',          'Klarna',           'BNPL'],
    ['affirm',          'Affirm',           'BNPL'],
    ['paddle',          'Paddle',           'MoR for SaaS'],
    ['lemon-squeezy',   'Lemon Squeezy',    'MoR + subs'],
    ['gumroad',         'Gumroad',          'Sell digital products'],
    ['polar',           'Polar',            'Devtools monetization'],
    ['chargebee',       'Chargebee',        'Subscription billing'],
    ['recurly',         'Recurly',          'Subscription mgmt'],
    ['stripe-billing',  'Stripe Billing',   'Subs + usage'],
    ['coinbase-commerce','Coinbase Commerce','Crypto checkout'],
    ['plaid',           'Plaid',            'Bank data + payments',            { popular: true }],
    ['teller',          'Teller.io',        'Bank API'],
    ['wise',            'Wise',             'Multi-currency'],
    ['revolut-business','Revolut Business', 'Cards + FX'],
    ['brex',            'Brex',             'Startup banking'],
    ['mercury',         'Mercury',          'Startup banking'],
    ['ramp',            'Ramp',             'Cards + spend'],
    ['airwallex',       'Airwallex',        'Global payments'],
    ['payu',            'PayU',             'EM payments'],
    ['cashfree',        'Cashfree',         'India payouts + payments'],
    ['phonepe',         'PhonePe Business', 'UPI India'],
    ['paytm',           'Paytm Business',   'India payments'],
    ['gpay-business',   'Google Pay Business','UPI accept'],
  ]),
  ...group('ecommerce', [
    ['shopify',         'Shopify',          'Storefront + orders + inventory', { popular: true, toolCount: 22 }],
    ['woocommerce',     'WooCommerce',      'WP ecom'],
    ['bigcommerce',     'BigCommerce',      'SaaS ecom'],
    ['magento',         'Adobe Magento',    'Enterprise ecom'],
    ['wix',             'Wix Stores',       'Wix ecom'],
    ['squarespace',     'Squarespace Commerce','SQSP ecom'],
    ['webflow-ecom',    'Webflow Ecom',     'Webflow stores'],
    ['etsy',            'Etsy',             'Handmade marketplace'],
    ['ebay',            'eBay',             'Marketplace'],
    ['amazon-seller',   'Amazon Seller',    'Amazon SP-API',                   { popular: true }],
    ['walmart-seller',  'Walmart Marketplace','Walmart sellers'],
    ['flipkart-seller', 'Flipkart Seller',  'India ecom'],
    ['meesho-seller',   'Meesho Supplier',  'India social ecom'],
    ['amazon-india',    'Amazon India',     'India MP'],
    ['shopee',          'Shopee',           'SEA marketplace'],
    ['lazada',          'Lazada',           'SEA marketplace'],
    ['mercado-libre',   'Mercado Libre',    'LatAm marketplace'],
    ['faire',           'Faire',            'B2B wholesale'],
    ['tundra',          'Tundra',           'Wholesale MP'],
    ['printful',        'Printful',         'POD fulfillment'],
    ['printify',        'Printify',         'POD'],
    ['gelato',          'Gelato',           'POD'],
    ['easyship',        'Easyship',         'Shipping API'],
    ['shipstation',     'ShipStation',      'Shipping mgmt'],
    ['shiprocket',      'Shiprocket',       'India shipping'],
    ['delhivery',       'Delhivery',        'India logistics'],
    ['shyplite',        'Shyplite',         'India shipping'],
  ]),
  ...group('hr-recruit', [
    ['workday',         'Workday',          'Enterprise HCM'],
    ['bamboohr',        'BambooHR',         'SMB HRIS',                        { popular: true }],
    ['gusto',           'Gusto',            'US payroll + benefits'],
    ['rippling',        'Rippling',         'HR + IT + finance'],
    ['deel',            'Deel',             'Global contractors',              { popular: true }],
    ['remote-com',      'Remote.com',       'Global hiring'],
    ['justworks',       'Justworks',        'PEO + payroll'],
    ['zenefits',        'Zenefits',         'HR platform'],
    ['personio',        'Personio',         'EU HR'],
    ['hibob',           'HiBob',            'People platform'],
    ['lever',           'Lever',            'ATS'],
    ['greenhouse',      'Greenhouse',       'ATS',                             { popular: true }],
    ['workable',        'Workable',         'Hiring'],
    ['ashby',           'Ashby',            'Modern ATS'],
    ['teamtailor',      'Teamtailor',       'EU ATS'],
    ['recruitee',       'Recruitee',        'Collab hiring'],
    ['smartrecruiters', 'SmartRecruiters',  'Talent acquisition'],
    ['jazzhr',          'JazzHR',           'SMB ATS'],
    ['breezyhr',        'BreezyHR',         'SMB ATS'],
    ['jobvite',         'Jobvite',          'Talent platform'],
    ['linkedin-talent', 'LinkedIn Talent',  'Recruiter API'],
    ['naukri',          'Naukri.com',       'India jobs'],
    ['indeed',          'Indeed',           'Global jobs'],
    ['otta',            'Otta',             'Tech jobs'],
    ['hired',           'Hired',            'Tech hiring marketplace'],
  ]),
  ...group('finance', [
    ['quickbooks',      'QuickBooks',       'Accounting',                      { popular: true, toolCount: 16 }],
    ['xero',            'Xero',             'Accounting',                      { popular: true }],
    ['freshbooks',      'FreshBooks',       'Invoicing + accounting'],
    ['wave',            'Wave',             'Free accounting'],
    ['sage',            'Sage',             'Accounting + ERP'],
    ['netsuite',        'NetSuite',         'Oracle ERP'],
    ['zoho-books',      'Zoho Books',       'Accounting'],
    ['tally-solutions', 'Tally Solutions',  'India accounting'],
    ['vyapar',          'Vyapar',           'India SMB billing'],
    ['cleartax',        'ClearTax',         'India tax'],
    ['recko',           'Recko',            'Recon'],
    ['profitwell',      'ProfitWell',       'SaaS metrics'],
    ['baremetrics',     'Baremetrics',      'SaaS analytics'],
    ['chartmogul',      'ChartMogul',       'Subscription analytics'],
    ['stripe-sigma',    'Stripe Sigma',     'Stripe SQL'],
    ['expensify',       'Expensify',        'Expense reports'],
    ['ramp-finance',    'Ramp',             'Spend mgmt'],
    ['airbase',         'Airbase',          'Spend mgmt'],
    ['divvy',           'Divvy / BILL',     'Spend + cards'],
    ['mercury-treasury','Mercury Treasury', 'Startup treasury'],
  ]),
  ...group('design', [
    ['figma',           'Figma',            'Design + comments + components',  { popular: true, toolCount: 13 }],
    ['sketch',          'Sketch',           'Mac design'],
    ['adobe-xd',        'Adobe XD',         'Adobe design'],
    ['adobe-photoshop', 'Adobe Photoshop',  'Image editing'],
    ['adobe-illustrator','Adobe Illustrator','Vector design'],
    ['adobe-creative-cloud','Adobe Creative Cloud','Assets + libraries'],
    ['canva',           'Canva',            'Templates + designs',             { popular: true }],
    ['framer',          'Framer',           'Sites + prototypes'],
    ['penpot',          'Penpot',           'OSS Figma alt'],
    ['affinity',        'Affinity',         'Serif design suite'],
    ['invision',        'InVision',         'Prototype + collab'],
    ['marvel',          'Marvel',           'Prototypes'],
    ['balsamiq',        'Balsamiq',         'Wireframes'],
    ['whimsical',       'Whimsical',        'Diagrams + wireframes'],
    ['excalidraw',      'Excalidraw',       'Hand-drawn diagrams'],
    ['tldraw',          'tldraw',           'Whiteboard'],
    ['miro',            'Miro',             'Visual collab'],
    ['mural',           'Mural',            'Visual collab'],
    ['figjam',          'FigJam',           'Whiteboard by Figma'],
    ['lucidchart',      'Lucidchart',       'Diagrams'],
    ['lucidspark',      'Lucidspark',       'Whiteboard'],
    ['eraser',          'Eraser',           'Engineering docs'],
    ['icons8',          'Icons8',           'Icons + photos'],
    ['flaticon',        'Flaticon',         'Icon library'],
    ['unsplash',        'Unsplash',         'Free photos'],
    ['pexels',          'Pexels',           'Stock photos'],
    ['pixabay',         'Pixabay',          'Free media'],
  ]),
  ...group('scheduling', [
    ['calendly',        'Calendly',         'Scheduling links',                { popular: true, toolCount: 8 }],
    ['cal-com',         'Cal.com',          'OSS scheduling',                  { popular: true }],
    ['savvycal',        'SavvyCal',         'Modern scheduling'],
    ['tidycal',         'TidyCal',          'Affordable scheduling'],
    ['acuity',          'Acuity Scheduling','Squarespace scheduling'],
    ['scheduleonce',    'OnceHub',          'Meeting scheduling'],
    ['youcanbookme',    'YouCanBookMe',     'Booking pages'],
    ['doodle',          'Doodle',           'Group polls'],
    ['when2meet',       'When2meet',        'Free group sched'],
    ['motion',          'Motion',           'AI calendar'],
    ['reclaim-ai',      'Reclaim.ai',       'AI scheduling'],
    ['clockwise',       'Clockwise',        'Calendar AI'],
    ['fantastical',     'Fantastical',      'Apple calendar app'],
    ['vimcal',          'Vimcal',           'Speed calendar'],
  ]),
  ...group('forms', [
    ['typeform',        'Typeform',         'Conversational forms',            { popular: true, toolCount: 8 }],
    ['tally-forms',     'Tally',            'Free forms',                      { popular: true }],
    ['jotform',         'Jotform',          'Form builder'],
    ['google-forms',    'Google Forms',     'Free forms'],
    ['microsoft-forms', 'Microsoft Forms',  'MS forms'],
    ['formspree',       'Formspree',        'Form backend'],
    ['formstack',       'Formstack',        'Enterprise forms'],
    ['paperform',       'Paperform',        'Custom forms'],
    ['feathery',        'Feathery',         'No-code forms'],
    ['cognito-forms',   'Cognito Forms',    'Powerful forms'],
    ['surveymonkey',    'SurveyMonkey',     'Surveys'],
    ['qualtrics',       'Qualtrics',        'Enterprise XM'],
    ['surveysparrow',   'SurveySparrow',    'Conversational surveys'],
    ['userpilot',       'Userpilot',        'In-app surveys'],
    ['delighted',       'Delighted',        'NPS + CSAT'],
    ['refiner',         'Refiner',          'User research'],
  ]),
  ...group('storage-cloud', [
    ['aws',             'AWS',              'EC2, S3, Lambda, RDS, …',         { popular: true, toolCount: 30 }],
    ['gcp',             'Google Cloud',     'GCE, GCS, Functions, BigQuery',   { popular: true }],
    ['azure',           'Microsoft Azure',  'VMs, Blob, Functions, SQL',       { popular: true }],
    ['digitalocean',    'DigitalOcean',     'Droplets, Spaces, Apps'],
    ['linode',          'Linode (Akamai)',  'Cloud + storage'],
    ['vultr',           'Vultr',            'Compute + storage'],
    ['hetzner',         'Hetzner',          'EU cloud + storage'],
    ['ovhcloud',        'OVHcloud',         'EU cloud'],
    ['scaleway',        'Scaleway',         'EU cloud'],
    ['oracle-cloud',    'Oracle Cloud',     'OCI compute + storage'],
    ['ibm-cloud',       'IBM Cloud',        'Enterprise cloud'],
    ['aws-s3',          'Amazon S3',        'Object storage'],
    ['cloudflare-r2',   'Cloudflare R2',    'S3 alt, no egress'],
    ['backblaze',       'Backblaze B2',     'Cheap object storage'],
    ['wasabi',          'Wasabi',           'S3 alt'],
    ['storj',           'Storj',            'Decentralized storage'],
    ['filebase',        'Filebase',         'IPFS object storage'],
    ['dropbox',         'Dropbox',          'Cloud files',                     { popular: true }],
    ['onedrive',        'OneDrive',         'Microsoft files',                 { popular: true }],
    ['box',             'Box',              'Enterprise files'],
    ['mega',            'MEGA',             'Encrypted storage'],
    ['pcloud',          'pCloud',           'Lifetime storage'],
    ['sync-com',        'Sync.com',         'Encrypted cloud'],
    ['tresorit',        'Tresorit',         'Secure files'],
    ['icloud-drive',    'iCloud Drive',     'Apple files'],
  ]),
  ...group('auth-identity', [
    ['auth0',           'Auth0',            'Identity platform',               { popular: true, toolCount: 9 }],
    ['clerk',           'Clerk',            'Auth for React/Next',             { popular: true }],
    ['workos',          'WorkOS',           'SSO + SCIM for enterprise'],
    ['okta',            'Okta',             'Enterprise IdP'],
    ['onelogin',        'OneLogin',         'IAM'],
    ['stytch',          'Stytch',           'Passwordless auth'],
    ['magic',           'Magic',            'Web3 + magic links'],
    ['hanko',           'Hanko',            'Passkey auth'],
    ['lucia',           'Lucia Auth',       'OSS TS auth library'],
    ['better-auth',     'Better Auth',      'Modern OSS auth'],
    ['fusionauth',      'FusionAuth',       'Self-hosted IAM'],
    ['keycloak',        'Keycloak',         'OSS IAM'],
    ['authentik',       'Authentik',        'OSS IdP'],
    ['authelia',        'Authelia',         'OSS auth proxy'],
    ['supertokens',     'SuperTokens',      'OSS auth'],
    ['frontegg',        'Frontegg',         'Self-serve B2B auth'],
    ['descope',         'Descope',          'No-code auth flows'],
    ['kinde',           'Kinde',            'Auth + feature flags'],
    ['supabase-auth',   'Supabase Auth',    'Supabase identity'],
    ['firebase-auth',   'Firebase Auth',    'Google identity'],
  ]),
  ...group('devtools', [
    ['postman',         'Postman',          'API workspaces + collections',    { popular: true }],
    ['insomnia',        'Insomnia',         'API client + design'],
    ['hoppscotch',      'Hoppscotch',       'OSS API client'],
    ['bruno',           'Bruno',            'Git-friendly API client'],
    ['mockoon',         'Mockoon',          'Local API mocks'],
    ['stoplight',       'Stoplight',        'API design'],
    ['readme',          'ReadMe',           'API docs'],
    ['mintlify',        'Mintlify',         'Beautiful docs'],
    ['scalar',          'Scalar',           'API docs + ref'],
    ['gitguardian',     'GitGuardian',      'Secret scanning'],
    ['mend',            'Mend',             'App security'],
    ['snyk-cli',        'Snyk CLI',         'Vuln scan CLI'],
    ['codacy',          'Codacy',           'Quality + security'],
    ['codeclimate',     'CodeClimate',      'Maintainability'],
    ['deepsource',      'DeepSource',       'Static analysis'],
    ['cypress',         'Cypress Cloud',    'E2E test runs'],
    ['playwright',      'Playwright',       'E2E tests'],
    ['percy',           'Percy',            'Visual testing'],
    ['chromatic',       'Chromatic',        'Storybook visual review'],
    ['storybook',       'Storybook',        'Component dev'],
    ['launchdarkly',    'LaunchDarkly',     'Feature flags',                   { popular: true }],
    ['posthog-flags',   'PostHog Flags',    'OSS feature flags'],
    ['unleash',         'Unleash',          'OSS flags'],
    ['split-io',        'Split.io',         'Feature flags + experiments'],
    ['flagsmith',       'Flagsmith',        'OSS flags'],
    ['growthbook',      'GrowthBook',       'OSS experiments + flags'],
    ['optimizely',      'Optimizely',       'Experiments'],
    ['vwo',             'VWO',              'A/B testing'],
  ]),
  ...group('media', [
    ['youtube-data',    'YouTube Data API', 'Videos, playlists, comments'],
    ['vimeo',           'Vimeo',            'Video hosting'],
    ['loom',            'Loom',             'Async video',                     { popular: true }],
    ['mux',             'Mux',              'Video infra API'],
    ['cloudinary',      'Cloudinary',       'Media CDN + transform',           { popular: true }],
    ['imagekit',        'ImageKit',         'Image CDN'],
    ['bunny-net',       'Bunny.net',        'CDN + storage + video'],
    ['twitch',          'Twitch',           'Streaming + chat'],
    ['spotify',         'Spotify',          'Music API'],
    ['apple-music',     'Apple Music',      'Music API'],
    ['soundcloud',      'SoundCloud',       'Audio platform'],
    ['anchor',          'Spotify for Podcasters','Podcasts'],
    ['descript',        'Descript',         'Audio/video editing'],
    ['otter-ai',        'Otter.ai',         'Meeting transcripts'],
    ['fireflies-ai',    'Fireflies.ai',     'AI meeting notes'],
    ['grain',           'Grain',            'Sales call recording'],
    ['gong',            'Gong',             'Revenue intel'],
    ['chorus-ai',       'Chorus.ai',        'Conversation intel'],
    ['rev',             'Rev',              'Transcription'],
    ['veed-io',         'VEED.IO',          'Online video editor'],
    ['capcut',          'CapCut',           'TikTok video editor'],
    ['canva-video',     'Canva Video',      'Video editor'],
  ]),
  ...group('misc', [
    ['ifttt',           'IFTTT',            'Applets across apps'],
    ['zapier',          'Zapier',           'Zaps + tables'],
    ['make',            'Make (Integromat)','Visual automations'],
    ['n8n',             'n8n',              'OSS automation',                  { popular: true }],
    ['pipedream',       'Pipedream',        'Code-friendly workflows'],
    ['windmill',        'Windmill',         'OSS workflows'],
    ['workato',         'Workato',          'Enterprise iPaaS'],
    ['tray-io',         'Tray.ai',          'iPaaS'],
    ['boomi',           'Boomi',            'iPaaS'],
    ['mulesoft',        'MuleSoft',         'Salesforce iPaaS'],
    ['retool',          'Retool',           'Internal tools'],
    ['budibase',        'Budibase',         'OSS internal tools'],
    ['appsmith',        'Appsmith',         'OSS internal tools'],
    ['glide',           'Glide',            'Apps from sheets'],
    ['softr',           'Softr',            'No-code from Airtable'],
    ['bubble',          'Bubble',           'No-code apps'],
    ['adalo',           'Adalo',            'No-code mobile'],
    ['flutterflow',     'FlutterFlow',      'Flutter no-code'],
    ['weather-api',     'OpenWeather',      'Weather data'],
    ['weatherapi',      'WeatherAPI.com',   'Weather + forecast'],
    ['nasa-api',        'NASA Open Data',   'NASA datasets'],
    ['wolfram-alpha',   'Wolfram Alpha',    'Computational answers'],
    ['wikipedia',       'Wikipedia',        'Articles + search'],
    ['wikidata',        'Wikidata',         'Structured knowledge'],
    ['archive-org',     'Internet Archive', 'Wayback + scholar'],
    ['github-gist',     'GitHub Gist',      'Snippets'],
    ['pastebin',        'Pastebin',         'Paste sharing'],
    ['hastebin',        'Hastebin',         'OSS paste'],
    ['imgur',           'Imgur',            'Image hosting'],
    ['giphy',           'GIPHY',            'GIFs'],
    ['tenor',           'Tenor',            'GIFs'],
    ['unsplash-api',    'Unsplash API',     'Free photos API'],
    ['stripe-atlas',    'Stripe Atlas',     'Co. formation'],
    ['firstbase',       'Firstbase',        'US company formation'],
    ['clerky',          'Clerky',           'Startup legal'],
    ['carta',           'Carta',            'Cap tables'],
    ['pulley',          'Pulley',           'Cap tables'],
    ['vouch',           'Vouch',            'Startup insurance'],
    ['embroker',        'Embroker',         'Business insurance'],
    ['next-insurance',  'Next Insurance',   'SMB insurance'],
    ['drata',           'Drata',            'SOC 2 + compliance'],
    ['vanta',           'Vanta',            'SOC 2 automation'],
    ['secureframe',     'Secureframe',      'Compliance automation'],
    ['onetrust',        'OneTrust',         'Privacy + compliance'],
    ['osano',           'Osano',            'Cookie + privacy'],
    ['didomi',          'Didomi',           'Consent platform'],
    ['snowflake-cortex','Snowflake Cortex', 'In-warehouse AI'],
    ['databricks-genie','Databricks AI/BI', 'BI Genie + agents'],
  ]),

  // ---- 2026 expansion: Meta family, vibe-coding, AI video/image, creator, India ----
  ...group('social', [
    ['meta-business',   'Meta Business Suite', 'Manage FB + IG pages',           { popular: true }],
    ['facebook-ads',    'Meta Ads Manager',    'Run FB + IG + Threads ads',      { popular: true }],
    ['instagram-ads',   'Instagram Ads',       'IG ad campaigns'],
    ['whatsapp-cloud',  'WhatsApp Cloud API',  'WA business messaging'],
    ['threads-business','Threads Business',    'Meta micro-blog ads'],
    ['x-ads',           'X Ads',               'Twitter/X advertising'],
    ['tiktok-ads',      'TikTok Ads',          'TikTok ad manager'],
    ['linkedin-ads',    'LinkedIn Ads',        'B2B ad campaigns'],
    ['pinterest-ads',   'Pinterest Ads',       'Pin promotion'],
    ['snap-ads',        'Snapchat Ads',        'Snap ads manager'],
    ['reddit-ads',      'Reddit Ads',          'Subreddit advertising'],
  ]),
  ...group('dev-code', [
    ['cursor',          'Cursor',              'AI code editor',                 { popular: true, toolCount: 8 }],
    ['windsurf',        'Windsurf',            'Codeium AI IDE'],
    ['cline',           'Cline',               'Autonomous coding agent'],
    ['continue-dev',    'Continue',            'OSS AI coding assistant'],
    ['v0',              'v0 by Vercel',        'AI UI generator',                { popular: true }],
    ['lovable',         'Lovable',             'AI app builder',                 { popular: true }],
    ['bolt-new',        'Bolt.new',            'WebContainer AI dev',            { popular: true }],
    ['replit-agent',    'Replit Agent',        'AI agent in Replit'],
    ['devin',           'Devin AI',            'Cognition autonomous SWE'],
    ['tempo-labs',      'Tempo Labs',          'AI design-to-code'],
    ['builder-io',      'Builder.io',          'Visual headless CMS'],
    ['e2b',             'E2B',                 'Code interpreter sandboxes'],
    ['daytona',         'Daytona',             'Cloud dev environments'],
    ['warp',            'Warp Terminal',       'AI terminal'],
    ['raycast-dev',     'Raycast (Developer)', 'Mac productivity launcher',      { popular: true }],
  ]),
  ...group('ai-ml', [
    ['midjourney',      'Midjourney',          'AI image generation',            { popular: true, toolCount: 6 }],
    ['flux',            'Flux (Black Forest)', 'Open-source image model'],
    ['ideogram',        'Ideogram',            'Text-aware image gen'],
    ['recraft',         'Recraft',             'AI vector + raster'],
    ['fal-ai',          'FAL AI',              'Fast inference platform'],
    ['leonardo-ai',     'Leonardo AI',         'Game-art image gen'],
    ['krea-ai',         'Krea AI',             'Realtime AI gen'],
    ['playground-ai',   'Playground AI',       'Free AI image gen'],
    ['pika',            'Pika',                'AI video gen'],
    ['luma-dream',      'Luma Dream Machine',  'AI video + 3D'],
    ['kling',           'Kling AI',            'High-quality AI video'],
    ['heygen',          'HeyGen',              'AI avatar videos',               { popular: true }],
    ['synthesia',       'Synthesia',           'AI presenter video'],
    ['d-id',            'D-ID',                'AI talking avatars'],
    ['hedra',           'Hedra',               'Character animation'],
    ['captions-ai',     'Captions',            'AI video captions + edit'],
    ['suno',            'Suno',                'AI music generation',            { popular: true }],
    ['udio',            'Udio',                'AI music gen'],
    ['play-ht',         'Play.ht',             'AI voice synthesis'],
    ['hume-ai',         'Hume AI',             'Emotional voice AI'],
    ['kagi',            'Kagi Search',         'Premium search engine'],
    ['brave-search',    'Brave Search',        'Independent search index'],
    ['tavily',          'Tavily',              'AI search API'],
    ['glean',           'Glean',               'Enterprise AI search'],
    ['lindy',           'Lindy',               'AI agent platform'],
    ['relevance-ai',    'Relevance AI',        'AI workforce'],
    ['crew-ai',         'CrewAI',              'Multi-agent framework'],
    ['langchain',       'LangChain',           'LLM app framework'],
    ['llamaindex',      'LlamaIndex',          'RAG framework'],
    ['vellum',          'Vellum',              'LLM ops platform'],
    ['galileo',         'Galileo',             'LLM evals'],
    ['sarvam-ai',       'Sarvam AI',           'India multilingual AI'],
    ['krutrim',         'Krutrim',             'Ola India LLM'],
    ['poe',             'Poe by Quora',        'Multi-model chat'],
    ['perplexity-spaces','Perplexity Spaces',  'AI research workspace'],
  ]),
  ...group('productivity', [
    ['granola',         'Granola',             'AI meeting notes',               { popular: true }],
    ['fellow-app',      'Fellow',              'Meeting + collab'],
    ['fathom-meet',     'Fathom',              'AI meeting recorder'],
    ['tactiq',          'Tactiq',              'Meeting transcripts'],
    ['scribe',          'Scribe',              'Auto-generated guides'],
    ['krisp',           'Krisp',               'AI noise removal'],
    ['notion-ai',       'Notion AI',           'Notion AI features'],
    ['mem-mosaic',      'Mem Mosaic',          'AI work assistant'],
    ['samepage',        'SamePage',            'AI work OS'],
    ['arc-browser',     'Arc Browser',         'Modern AI browser'],
    ['arc-search',      'Arc Search',          'Mobile AI browser'],
    ['comet-perplexity','Perplexity Comet',    'Agentic AI browser'],
    ['dia-browser',     'Dia',                 'Browser Company AI browser'],
    ['beeper',          'Beeper',              'Universal chat client'],
    ['readwise',        'Readwise',            'Highlights + reading'],
    ['matter',          'Matter',              'Read-later + AI'],
  ]),
  ...group('email', [
    ['superhuman',      'Superhuman',          'Fast email',                     { popular: true }],
    ['shortwave',       'Shortwave',           'AI Gmail client'],
    ['fyxer-ai',        'Fyxer AI',            'AI email assistant'],
    ['mailbird',        'Mailbird',            'Email client'],
    ['spike-email',     'Spike',               'Conversational email'],
    ['hey-world',       'HEY World',           'Public newsletter'],
  ]),
  ...group('payments', [
    ['coinbase',        'Coinbase',            'Crypto exchange API',            { popular: true }],
    ['binance',         'Binance',             'Crypto exchange API'],
    ['kraken',          'Kraken',              'Crypto exchange API'],
    ['alchemy',         'Alchemy',             'Web3 dev platform'],
    ['infura',          'Infura',              'Ethereum infra'],
    ['etherscan',       'Etherscan',           'Ethereum explorer'],
    ['opensea',         'OpenSea',             'NFT marketplace API'],
    ['razorpay-x',      'Razorpay X',          'India business banking',         { popular: true }],
    ['kuvera',          'Kuvera',              'India investment platform'],
    ['groww',           'Groww',               'India broking API'],
    ['zerodha-kite',    'Zerodha Kite',        'India broker API'],
    ['upstox',          'Upstox',              'India broking API'],
    ['icici-imobile',   'ICICI iMobile',       'India banking API'],
    ['hdfc-bank',       'HDFC Bank',           'India banking API'],
    ['polygon-io',      'Polygon.io',          'Stock + crypto market data'],
    ['alpaca',          'Alpaca',              'US stock trading API'],
  ]),
  ...group('auth-identity', [
    ['1password',       '1Password',           'Password manager',               { popular: true }],
    ['bitwarden',       'Bitwarden',           'OSS password manager'],
    ['lastpass',        'LastPass',            'Password manager'],
    ['dashlane',        'Dashlane',            'Password manager'],
    ['proton-pass',     'Proton Pass',         'Encrypted password manager'],
    ['digilocker',      'DigiLocker',          'India govt e-documents'],
    ['aadhaar-api',     'Aadhaar e-KYC',       'India identity API'],
  ]),
  ...group('marketing', [
    // Advertising platforms — high value for marketers running AI on ad data.
    ['google-ads',      'Google Ads',          'Campaigns, keywords, performance', { popular: true, toolCount: 12 }],
    ['patreon',         'Patreon',             'Creator memberships',            { popular: true }],
    ['ko-fi',           'Ko-fi',               'Creator donations'],
    ['buy-me-coffee',   'Buy Me a Coffee',     'Creator tips'],
    ['memberful',       'Memberful',           'Membership platform'],
    ['kajabi',          'Kajabi',              'Course + community',             { popular: true }],
    ['teachable',       'Teachable',           'Online courses'],
    ['thinkific',       'Thinkific',           'Course platform'],
    ['circle-so',       'Circle.so',           'Community platform'],
    ['mighty-networks', 'Mighty Networks',     'Community platform'],
    ['discourse',       'Discourse',           'OSS community forum'],
    ['podia',           'Podia',               'Sell digital + courses'],
    ['skool',           'Skool',               'Community + courses'],
  ]),
  ...group('media', [
    ['picsart',         'Picsart',             'Photo editor + AI'],
    ['photoroom',       'PhotoRoom',           'AI background removal'],
    ['runway-gen3',     'Runway Gen-3',        'Cinematic AI video'],
    ['descript-overdub','Descript Overdub',    'AI voice clone'],
    ['eleven-labs-dub', 'ElevenLabs Dubbing',  'AI voice translation'],
    ['veed-ai',         'VEED AI',             'Online video editor'],
  ]),
  ...group('support', [
    ['intercom-fin',    'Intercom Fin',        'AI customer support agent'],
    ['ada',             'Ada',                 'AI customer service'],
    ['cresta',          'Cresta',              'Sales AI coaching'],
    ['kustomer',        'Kustomer',            'CRM + support'],
    ['freshchat',       'Freshchat',           'Live + bot chat'],
    ['gladly',          'Gladly',              'Customer service platform'],
  ]),
  ...group('misc', [
    ['ola-maps',        'Ola Maps',            'India maps API'],
    ['mappls',          'Mappls (MapmyIndia)', 'India maps + nav'],
    ['indiastack',      'India Stack APIs',    'UPI + Aadhaar + DigiLocker'],
    ['gst-india',       'GST India',           'India tax filing API'],
    ['epfo',            'EPFO',                'India provident fund'],
    ['mapbox',          'Mapbox',              'Maps + nav SDK'],
    ['google-maps',     'Google Maps Platform','Maps + Places + Geocoding'],
    ['here-maps',       'HERE Maps',           'Location + nav'],
    ['fingerprintjs',   'Fingerprint',         'Visitor identification'],
    ['statsig',         'Statsig',             'Experiments + flags'],
    ['eppo',            'Eppo',                'Experimentation'],
    ['ai-village',      'AI Village',          'Agent marketplace'],
    ['smithery-ai',     'Smithery',            'MCP server registry'],
    ['composio-toolset','Composio Toolset',    'Multi-tool agent platform'],
    ['arcade-ai',       'Arcade.dev',          'AI tool platform'],
  ]),
];

// ---------------------------------------------------------------------------

export const CONNECT_APPS: ConnectApp[] = [...LIVE, ...CATALOG];

// Stats used in the marketing hero + meta. Approximate tool counts grow
// roughly linearly with apps — we hand-round to the nearest big number
// so the claims stay honest as we add providers.
export const CONNECT_STATS = {
  totalApps: CONNECT_APPS.length,            // 700+
  totalApproxTools: 1200,                    // ~1.7 tools/app avg
  agentIntegrations: 50,                     // Claude / Cursor / Cline / Windsurf / Continue / OpenAI / etc.
  liveProviders: LIVE.length,
} as const;

export function listAppsByCategory(category: ConnectCategory): ConnectApp[] {
  return CONNECT_APPS.filter((a) => a.category === category);
}

export function getAppBySlug(slug: string): ConnectApp | undefined {
  return CONNECT_APPS.find((a) => a.slug === slug);
}

export function popularApps(limit = 18): ConnectApp[] {
  return CONNECT_APPS.filter((a) => a.popular).slice(0, limit);
}

export function liveApps(): ConnectApp[] {
  return CONNECT_APPS.filter((a) => a.status === 'live');
}

/**
 * Lightweight search — name, slug, tagline. Case-insensitive substring.
 * Real fuzzy search lives in /lib/fuzzy-search.ts; we keep this dumb-fast
 * because the catalog is huge and the UI does client-side filtering.
 */
export function searchApps(query: string): ConnectApp[] {
  const q = query.trim().toLowerCase();
  if (!q) return CONNECT_APPS;
  return CONNECT_APPS.filter(
    (a) =>
      a.name.toLowerCase().includes(q) ||
      a.slug.includes(q) ||
      a.tagline.toLowerCase().includes(q),
  );
}
