// MCP (Model Context Protocol) connector directory — curated for StackPicks.
// Snapshot: May 2026. Update by editing this file + redeploy (no DB needed).
//
// Each entry maps to a real MCP server that gives Claude / Cursor / Cline /
// Windsurf direct tool access to a SaaS, database, or local resource. We list
// the install command (npx / uv / docker) so users can paste it into their
// MCP client config and connect in <60 seconds.
//
// Source field reflects who maintains the server, not who owns the underlying
// product — e.g. `slack` server is built by Anthropic but talks to Slack.

export type MCPCategory =
  | 'ai-llm'
  | 'database'
  | 'devops'
  | 'productivity'
  | 'communication'
  | 'design'
  | 'search-web'
  | 'browser'
  | 'payments'
  | 'cloud'
  | 'storage'
  | 'analytics'
  | 'ecommerce'
  | 'crm'
  | 'code-dev'
  | 'security'
  | 'media'
  | 'vector-db';

export const MCP_CATEGORIES: { slug: MCPCategory; name: string; icon: string }[] = [
  { slug: 'ai-llm',         name: 'AI / LLM',           icon: 'brain' },
  { slug: 'database',       name: 'Database',           icon: 'database' },
  { slug: 'vector-db',      name: 'Vector DB',          icon: 'layers' },
  { slug: 'devops',         name: 'DevOps / Infra',     icon: 'server' },
  { slug: 'cloud',          name: 'Cloud',              icon: 'cloud' },
  { slug: 'productivity',   name: 'Productivity',       icon: 'check-square' },
  { slug: 'communication',  name: 'Communication',      icon: 'message-square' },
  { slug: 'design',         name: 'Design',             icon: 'palette' },
  { slug: 'search-web',     name: 'Search / Web',       icon: 'search' },
  { slug: 'browser',        name: 'Browser Automation', icon: 'globe' },
  { slug: 'payments',       name: 'Payments',           icon: 'credit-card' },
  { slug: 'storage',        name: 'Storage',            icon: 'folder' },
  { slug: 'analytics',      name: 'Analytics',          icon: 'bar-chart' },
  { slug: 'ecommerce',      name: 'E-commerce',         icon: 'shopping-cart' },
  { slug: 'crm',            name: 'CRM',                icon: 'users' },
  { slug: 'code-dev',       name: 'Code & Dev tools',   icon: 'code' },
  { slug: 'security',       name: 'Security',           icon: 'shield' },
  { slug: 'media',          name: 'Media / Generative', icon: 'image' },
];

export interface MCPServer {
  slug: string;
  name: string;
  source: 'official' | 'vendor' | 'community';
  publisher: string;
  publisher_github?: string; // owner part of github.com/{owner}/{repo}
  github?: string;           // full owner/repo
  docs?: string;
  categories: MCPCategory[];
  description: string;       // 1 sentence what it does
  use_case: string;          // 1 sentence why an agent wants it
  install: {
    npx?: string;
    uvx?: string;
    docker?: string;
    pip?: string;
    remote?: string;         // remote MCP endpoint URL
  };
  transport: ('stdio' | 'http' | 'sse')[];
  requires_auth: boolean;
  auth_note?: string;        // e.g. "Bring your own API key"
  tags?: string[];
}

// =============================================================================
// THE LIST — 80+ MCP servers, May 2026 snapshot
// =============================================================================
export const MCP_SERVERS: MCPServer[] = [
  // ---------- OFFICIAL ANTHROPIC REFERENCE SERVERS ----------
  {
    slug: 'filesystem',
    name: 'Filesystem',
    source: 'official',
    publisher: 'Anthropic',
    publisher_github: 'modelcontextprotocol',
    github: 'modelcontextprotocol/servers',
    docs: 'https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem',
    categories: ['code-dev'],
    description: 'Read, write, list, and search files in scoped local directories.',
    use_case: 'Let the agent edit a project on disk without leaving the chat.',
    install: { npx: 'npx -y @modelcontextprotocol/server-filesystem /path/to/dir' },
    transport: ['stdio'],
    requires_auth: false,
    tags: ['fs', 'local'],
  },
  {
    slug: 'github',
    name: 'GitHub (official)',
    source: 'vendor',
    publisher: 'GitHub',
    publisher_github: 'github',
    github: 'github/github-mcp-server',
    docs: 'https://github.com/github/github-mcp-server',
    categories: ['code-dev', 'devops'],
    description: 'Full GitHub API access: issues, PRs, code search, Actions, repos.',
    use_case: 'Triage issues, open PRs, review code, run workflows from the agent.',
    install: { docker: 'docker run -i --rm -e GITHUB_PERSONAL_ACCESS_TOKEN ghcr.io/github/github-mcp-server' },
    transport: ['stdio', 'http'],
    requires_auth: true,
    auth_note: 'GitHub PAT or GitHub App token',
    tags: ['git', 'issues', 'pr'],
  },
  {
    slug: 'gitlab',
    name: 'GitLab',
    source: 'official',
    publisher: 'Anthropic',
    publisher_github: 'modelcontextprotocol',
    github: 'modelcontextprotocol/servers',
    categories: ['code-dev', 'devops'],
    description: 'GitLab projects, MRs, issues, pipelines via the GitLab REST API.',
    use_case: 'For self-hosted GitLab teams that want the same agent UX as GitHub.',
    install: { npx: 'npx -y @modelcontextprotocol/server-gitlab' },
    transport: ['stdio'],
    requires_auth: true,
    auth_note: 'GitLab personal access token',
  },
  {
    slug: 'google-drive',
    name: 'Google Drive',
    source: 'official',
    publisher: 'Anthropic',
    publisher_github: 'modelcontextprotocol',
    github: 'modelcontextprotocol/servers',
    categories: ['storage', 'productivity'],
    description: 'List, read, and search files in your Google Drive.',
    use_case: 'Pull a spec doc or sheet into the agent without copy-paste.',
    install: { npx: 'npx -y @modelcontextprotocol/server-gdrive' },
    transport: ['stdio'],
    requires_auth: true,
    auth_note: 'OAuth via Google Cloud project',
  },
  {
    slug: 'slack',
    name: 'Slack',
    source: 'official',
    publisher: 'Anthropic',
    publisher_github: 'modelcontextprotocol',
    github: 'modelcontextprotocol/servers',
    categories: ['communication'],
    description: 'Read channels, post messages, search history, manage threads.',
    use_case: 'Agent can DM teammates, summarize a channel, or post a release note.',
    install: { npx: 'npx -y @modelcontextprotocol/server-slack' },
    transport: ['stdio'],
    requires_auth: true,
    auth_note: 'Slack Bot User OAuth Token',
  },
  {
    slug: 'postgres',
    name: 'PostgreSQL',
    source: 'official',
    publisher: 'Anthropic',
    publisher_github: 'modelcontextprotocol',
    github: 'modelcontextprotocol/servers',
    categories: ['database'],
    description: 'Read-only SQL queries against a Postgres database with schema introspection.',
    use_case: 'Let the agent explore tables and answer data questions safely.',
    install: { npx: 'npx -y @modelcontextprotocol/server-postgres postgresql://user:pw@host/db' },
    transport: ['stdio'],
    requires_auth: true,
    auth_note: 'Postgres connection string',
  },
  {
    slug: 'sqlite',
    name: 'SQLite',
    source: 'official',
    publisher: 'Anthropic',
    publisher_github: 'modelcontextprotocol',
    github: 'modelcontextprotocol/servers',
    categories: ['database'],
    description: 'Read/write to a local SQLite file with schema and query tools.',
    use_case: 'Quickly inspect or edit a local app DB during dev.',
    install: { uvx: 'uvx mcp-server-sqlite --db-path /path/to/db.sqlite' },
    transport: ['stdio'],
    requires_auth: false,
  },
  {
    slug: 'puppeteer',
    name: 'Puppeteer',
    source: 'official',
    publisher: 'Anthropic',
    publisher_github: 'modelcontextprotocol',
    github: 'modelcontextprotocol/servers',
    categories: ['browser'],
    description: 'Headless Chrome — navigate, screenshot, click, evaluate JS.',
    use_case: 'Scrape data, automate flows, or visually QA a deploy.',
    install: { npx: 'npx -y @modelcontextprotocol/server-puppeteer' },
    transport: ['stdio'],
    requires_auth: false,
  },
  {
    slug: 'brave-search',
    name: 'Brave Search',
    source: 'official',
    publisher: 'Anthropic',
    publisher_github: 'modelcontextprotocol',
    github: 'modelcontextprotocol/servers',
    categories: ['search-web'],
    description: 'Web + local search using the Brave Search API. 2k free queries/mo.',
    use_case: 'Cheap, privacy-friendly web search for grounding the agent.',
    install: { npx: 'npx -y @modelcontextprotocol/server-brave-search' },
    transport: ['stdio'],
    requires_auth: true,
    auth_note: 'BRAVE_API_KEY (free tier available)',
  },
  {
    slug: 'fetch',
    name: 'Fetch',
    source: 'official',
    publisher: 'Anthropic',
    publisher_github: 'modelcontextprotocol',
    github: 'modelcontextprotocol/servers',
    categories: ['search-web'],
    description: 'Fetch a URL and convert to Markdown for the agent.',
    use_case: 'Quickest way to give the agent "read this URL" capability.',
    install: { uvx: 'uvx mcp-server-fetch' },
    transport: ['stdio'],
    requires_auth: false,
  },
  {
    slug: 'sequential-thinking',
    name: 'Sequential Thinking',
    source: 'official',
    publisher: 'Anthropic',
    publisher_github: 'modelcontextprotocol',
    github: 'modelcontextprotocol/servers',
    categories: ['ai-llm'],
    description: 'Forces the agent to plan in numbered, revisable steps.',
    use_case: 'Boosts reasoning on multi-step coding or research tasks.',
    install: { npx: 'npx -y @modelcontextprotocol/server-sequential-thinking' },
    transport: ['stdio'],
    requires_auth: false,
  },
  {
    slug: 'memory',
    name: 'Memory',
    source: 'official',
    publisher: 'Anthropic',
    publisher_github: 'modelcontextprotocol',
    github: 'modelcontextprotocol/servers',
    categories: ['ai-llm'],
    description: 'Persistent knowledge graph across sessions — entities, relations, observations.',
    use_case: 'Give the agent durable memory of users, projects, and decisions.',
    install: { npx: 'npx -y @modelcontextprotocol/server-memory' },
    transport: ['stdio'],
    requires_auth: false,
  },
  {
    slug: 'sentry',
    name: 'Sentry',
    source: 'vendor',
    publisher: 'Sentry',
    publisher_github: 'getsentry',
    github: 'getsentry/sentry-mcp',
    docs: 'https://docs.sentry.io/product/sentry-mcp/',
    categories: ['devops', 'analytics'],
    description: 'Query errors, performance issues, and replays directly from Sentry.',
    use_case: 'Agent fetches the stack trace, finds the bad commit, opens the PR.',
    install: { remote: 'https://mcp.sentry.dev/sse' },
    transport: ['sse', 'http'],
    requires_auth: true,
    auth_note: 'Sentry OAuth',
  },
  {
    slug: 'time',
    name: 'Time',
    source: 'official',
    publisher: 'Anthropic',
    publisher_github: 'modelcontextprotocol',
    github: 'modelcontextprotocol/servers',
    categories: ['productivity'],
    description: 'Current time, timezone conversion, scheduling math.',
    use_case: 'Stops the agent from hallucinating "today\'s date".',
    install: { uvx: 'uvx mcp-server-time' },
    transport: ['stdio'],
    requires_auth: false,
  },

  // ---------- VENDOR-OFFICIAL ----------
  {
    slug: 'cloudflare',
    name: 'Cloudflare',
    source: 'vendor',
    publisher: 'Cloudflare',
    publisher_github: 'cloudflare',
    github: 'cloudflare/mcp-server-cloudflare',
    docs: 'https://developers.cloudflare.com/agents/model-context-protocol/',
    categories: ['cloud', 'devops'],
    description: 'Workers, KV, R2, D1, Pages, DNS — full Cloudflare control plane.',
    use_case: 'Deploy a Worker, query D1, configure DNS without leaving the agent.',
    install: { remote: 'https://observability.mcp.cloudflare.com/sse' },
    transport: ['sse', 'http'],
    requires_auth: true,
    auth_note: 'Cloudflare OAuth',
  },
  {
    slug: 'stripe',
    name: 'Stripe',
    source: 'vendor',
    publisher: 'Stripe',
    publisher_github: 'stripe',
    github: 'stripe/agent-toolkit',
    docs: 'https://docs.stripe.com/agents',
    categories: ['payments'],
    description: 'Create customers, charges, products, refunds, subscriptions via Stripe API.',
    use_case: 'Let the agent issue refunds or look up a customer\'s subscription state.',
    install: { npx: 'npx -y @stripe/mcp --tools=all --api-key=sk_test_...' },
    transport: ['stdio', 'sse'],
    requires_auth: true,
    auth_note: 'Stripe restricted key recommended',
  },
  {
    slug: 'linear',
    name: 'Linear',
    source: 'vendor',
    publisher: 'Linear',
    publisher_github: 'linear',
    github: 'linear/mcp-server',
    docs: 'https://linear.app/docs/mcp',
    categories: ['productivity', 'code-dev'],
    description: 'Issues, projects, cycles, teams — full Linear graph.',
    use_case: 'Agent creates issues from a meeting note, moves them through workflow.',
    install: { remote: 'https://mcp.linear.app/sse' },
    transport: ['sse', 'http'],
    requires_auth: true,
    auth_note: 'Linear OAuth',
  },
  {
    slug: 'notion',
    name: 'Notion',
    source: 'vendor',
    publisher: 'Notion',
    publisher_github: 'makenotion',
    github: 'makenotion/notion-mcp-server',
    docs: 'https://developers.notion.com/docs/mcp',
    categories: ['productivity', 'storage'],
    description: 'Query databases, create pages, search workspace via Notion API.',
    use_case: 'Turn meeting notes into structured Notion pages with one prompt.',
    install: { npx: 'npx -y @notionhq/notion-mcp-server' },
    transport: ['stdio'],
    requires_auth: true,
    auth_note: 'Notion integration token',
  },
  {
    slug: 'atlassian',
    name: 'Atlassian (Jira + Confluence)',
    source: 'community',
    publisher: 'Sooperset',
    publisher_github: 'sooperset',
    github: 'sooperset/mcp-atlassian',
    categories: ['productivity', 'code-dev'],
    description: 'Jira tickets + Confluence pages — search, create, comment, transition.',
    use_case: 'Sync sprint work to Confluence release notes automatically.',
    install: { docker: 'docker run -i --rm -e JIRA_URL ghcr.io/sooperset/mcp-atlassian:latest' },
    transport: ['stdio'],
    requires_auth: true,
    auth_note: 'Atlassian API token',
  },
  {
    slug: 'supabase',
    name: 'Supabase',
    source: 'vendor',
    publisher: 'Supabase',
    publisher_github: 'supabase-community',
    github: 'supabase-community/supabase-mcp',
    docs: 'https://supabase.com/docs/guides/getting-started/mcp',
    categories: ['database', 'cloud'],
    description: 'Database, auth, storage, edge functions — full Supabase project ops.',
    use_case: 'Agent writes a migration, runs it, then queries the new table.',
    install: { npx: 'npx -y @supabase/mcp-server-supabase --access-token=sbp_...' },
    transport: ['stdio'],
    requires_auth: true,
    auth_note: 'Supabase Personal Access Token (sbp_…)',
  },
  {
    slug: 'neon',
    name: 'Neon',
    source: 'vendor',
    publisher: 'Neon',
    publisher_github: 'neondatabase',
    github: 'neondatabase/mcp-server-neon',
    docs: 'https://neon.tech/docs/ai/neon-mcp-server',
    categories: ['database', 'cloud'],
    description: 'Serverless Postgres branches — create, query, time-travel.',
    use_case: 'Spin up a DB branch for each agent task, throw away when done.',
    install: { npx: 'npx -y @neondatabase/mcp-server-neon start <NEON_API_KEY>' },
    transport: ['stdio'],
    requires_auth: true,
    auth_note: 'Neon API key',
  },
  {
    slug: 'mongodb',
    name: 'MongoDB',
    source: 'vendor',
    publisher: 'MongoDB',
    publisher_github: 'mongodb-js',
    github: 'mongodb-js/mongodb-mcp-server',
    docs: 'https://github.com/mongodb-js/mongodb-mcp-server',
    categories: ['database'],
    description: 'CRUD + aggregations on MongoDB Atlas or self-hosted clusters.',
    use_case: 'Inspect documents, build aggregation pipelines without the shell.',
    install: { npx: 'npx -y mongodb-mcp-server --connectionString="mongodb+srv://..."' },
    transport: ['stdio'],
    requires_auth: true,
    auth_note: 'MongoDB connection string',
  },
  {
    slug: 'mysql',
    name: 'MySQL',
    source: 'community',
    publisher: 'benborla',
    publisher_github: 'benborla',
    github: 'benborla/mcp-server-mysql',
    categories: ['database'],
    description: 'Query MySQL / MariaDB with schema introspection.',
    use_case: 'Same UX as the Postgres server, but for MySQL stacks.',
    install: { npx: 'npx -y @benborla29/mcp-server-mysql' },
    transport: ['stdio'],
    requires_auth: true,
    auth_note: 'MYSQL_HOST / USER / PASSWORD env',
  },
  {
    slug: 'redis',
    name: 'Redis',
    source: 'vendor',
    publisher: 'Redis',
    publisher_github: 'redis',
    github: 'redis/mcp-redis',
    categories: ['database'],
    description: 'GET, SET, list keys, vector search via RediSearch.',
    use_case: 'Inspect cache state and rate-limit counters during incidents.',
    install: { uvx: 'uvx --from git+https://github.com/redis/mcp-redis.git redis-mcp-server' },
    transport: ['stdio'],
    requires_auth: true,
    auth_note: 'REDIS_HOST + REDIS_PWD env',
  },
  {
    slug: 'elasticsearch',
    name: 'Elasticsearch',
    source: 'vendor',
    publisher: 'Elastic',
    publisher_github: 'elastic',
    github: 'elastic/mcp-server-elasticsearch',
    categories: ['database', 'search-web'],
    description: 'Full-text search and aggregations against Elastic clusters.',
    use_case: 'Agent searches logs, builds dashboards, finds patterns.',
    install: { npx: 'npx -y @elastic/mcp-server-elasticsearch' },
    transport: ['stdio'],
    requires_auth: true,
    auth_note: 'ES_URL + API key',
  },
  {
    slug: 'snowflake',
    name: 'Snowflake',
    source: 'community',
    publisher: 'Isaac Wasserman',
    publisher_github: 'isaacwasserman',
    github: 'isaacwasserman/mcp-snowflake-server',
    categories: ['database', 'analytics'],
    description: 'Run SQL on Snowflake warehouses with role-scoped access.',
    use_case: 'Analyst-style agent that drafts SQL and returns CSVs.',
    install: { uvx: 'uvx mcp-snowflake-server' },
    transport: ['stdio'],
    requires_auth: true,
    auth_note: 'Snowflake account / user / pwd',
  },
  {
    slug: 'airtable',
    name: 'Airtable',
    source: 'community',
    publisher: 'domdomegg',
    publisher_github: 'domdomegg',
    github: 'domdomegg/airtable-mcp-server',
    categories: ['database', 'productivity'],
    description: 'Read, write, search bases — full Airtable schema access.',
    use_case: 'No-code teams can let agents update CRM-style Airtables.',
    install: { npx: 'npx -y airtable-mcp-server' },
    transport: ['stdio'],
    requires_auth: true,
    auth_note: 'Airtable PAT',
  },

  // ---------- VECTOR DB ----------
  {
    slug: 'pinecone',
    name: 'Pinecone',
    source: 'community',
    publisher: 'sirmews',
    publisher_github: 'sirmews',
    github: 'sirmews/mcp-pinecone',
    categories: ['vector-db', 'ai-llm'],
    description: 'Upsert and query vectors in Pinecone serverless indexes.',
    use_case: 'Hot-load RAG data without writing pipeline code.',
    install: { uvx: 'uvx mcp-pinecone' },
    transport: ['stdio'],
    requires_auth: true,
    auth_note: 'PINECONE_API_KEY',
  },
  {
    slug: 'qdrant',
    name: 'Qdrant',
    source: 'vendor',
    publisher: 'Qdrant',
    publisher_github: 'qdrant',
    github: 'qdrant/mcp-server-qdrant',
    categories: ['vector-db', 'ai-llm'],
    description: 'Store and retrieve semantic memories in Qdrant collections.',
    use_case: 'Give the agent long-term semantic memory with embedded payloads.',
    install: { uvx: 'uvx mcp-server-qdrant' },
    transport: ['stdio'],
    requires_auth: true,
    auth_note: 'QDRANT_URL + API key (cloud or self-host)',
  },
  {
    slug: 'chroma',
    name: 'Chroma',
    source: 'vendor',
    publisher: 'Chroma',
    publisher_github: 'chroma-core',
    github: 'chroma-core/chroma-mcp',
    categories: ['vector-db', 'ai-llm'],
    description: 'Embedded or remote Chroma collections — add, query, get.',
    use_case: 'Local-first RAG for agents working on private documents.',
    install: { uvx: 'uvx chroma-mcp' },
    transport: ['stdio'],
    requires_auth: false,
  },
  {
    slug: 'weaviate',
    name: 'Weaviate',
    source: 'vendor',
    publisher: 'Weaviate',
    publisher_github: 'weaviate',
    github: 'weaviate/mcp-server-weaviate',
    categories: ['vector-db'],
    description: 'Hybrid search (vector + keyword) on Weaviate schemas.',
    use_case: 'Best when you need filters + vectors in the same query.',
    install: { npx: 'npx -y @weaviate/mcp-server' },
    transport: ['stdio'],
    requires_auth: true,
  },
  {
    slug: 'milvus',
    name: 'Milvus',
    source: 'vendor',
    publisher: 'Zilliz',
    publisher_github: 'zilliztech',
    github: 'zilliztech/mcp-server-milvus',
    categories: ['vector-db'],
    description: 'Open-source vector DB at billion-scale — collections, search, insert.',
    use_case: 'When Pinecone\'s pricing breaks at scale, this is the answer.',
    install: { uvx: 'uvx mcp-server-milvus' },
    transport: ['stdio'],
    requires_auth: true,
  },

  // ---------- BROWSER ----------
  {
    slug: 'playwright',
    name: 'Playwright',
    source: 'vendor',
    publisher: 'Microsoft',
    publisher_github: 'microsoft',
    github: 'microsoft/playwright-mcp',
    docs: 'https://github.com/microsoft/playwright-mcp',
    categories: ['browser', 'code-dev'],
    description: 'Real Playwright in a sandbox — navigate, click, evaluate, snapshot.',
    use_case: 'Better than Puppeteer for cross-browser testing and complex flows.',
    install: { npx: 'npx -y @playwright/mcp@latest' },
    transport: ['stdio'],
    requires_auth: false,
  },
  {
    slug: 'browserbase',
    name: 'Browserbase',
    source: 'vendor',
    publisher: 'Browserbase',
    publisher_github: 'browserbase',
    github: 'browserbase/mcp-server-browserbase',
    docs: 'https://docs.browserbase.com/integrations/mcp',
    categories: ['browser'],
    description: 'Cloud-hosted headless Chrome — stealth, residential IPs, session replay.',
    use_case: 'Scrape sites that block local Puppeteer / Playwright.',
    install: { npx: 'npx -y @browserbasehq/mcp' },
    transport: ['stdio', 'sse'],
    requires_auth: true,
    auth_note: 'BROWSERBASE_API_KEY',
  },
  {
    slug: 'firecrawl',
    name: 'Firecrawl',
    source: 'vendor',
    publisher: 'Mendable',
    publisher_github: 'mendableai',
    github: 'mendableai/firecrawl-mcp-server',
    docs: 'https://docs.firecrawl.dev/mcp',
    categories: ['browser', 'search-web'],
    description: 'Crawl entire sites, extract structured data, scrape into LLM-ready Markdown.',
    use_case: 'One tool replaces 80% of scraping infra for agent pipelines.',
    install: { npx: 'env FIRECRAWL_API_KEY=fc-... npx -y firecrawl-mcp' },
    transport: ['stdio'],
    requires_auth: true,
    auth_note: 'FIRECRAWL_API_KEY (free tier 500 pages/mo)',
  },
  {
    slug: 'apify',
    name: 'Apify',
    source: 'vendor',
    publisher: 'Apify',
    publisher_github: 'apify',
    github: 'apify/actors-mcp-server',
    categories: ['browser'],
    description: 'Run any Apify Actor (5,000+) — scrape Google, LinkedIn, IG, anything.',
    use_case: 'Use battle-tested public actors instead of writing your own scrapers.',
    install: { npx: 'npx -y @apify/actors-mcp-server' },
    transport: ['stdio'],
    requires_auth: true,
    auth_note: 'APIFY_TOKEN',
  },

  // ---------- SEARCH ----------
  {
    slug: 'perplexity',
    name: 'Perplexity',
    source: 'vendor',
    publisher: 'Perplexity',
    publisher_github: 'ppl-ai',
    github: 'ppl-ai/modelcontextprotocol',
    categories: ['search-web', 'ai-llm'],
    description: 'Sonar API — real-time web search with cited answers.',
    use_case: 'Best grounding for "what happened today" style questions.',
    install: { npx: 'npx -y @perplexity-ai/mcp-server-perplexity' },
    transport: ['stdio'],
    requires_auth: true,
    auth_note: 'PERPLEXITY_API_KEY',
  },
  {
    slug: 'exa',
    name: 'Exa',
    source: 'vendor',
    publisher: 'Exa',
    publisher_github: 'exa-labs',
    github: 'exa-labs/exa-mcp-server',
    categories: ['search-web'],
    description: 'Neural-search engine built for LLMs — semantic + keyword hybrid.',
    use_case: 'Better-than-Google for finding niche technical docs and papers.',
    install: { npx: 'npx -y exa-mcp-server' },
    transport: ['stdio'],
    requires_auth: true,
    auth_note: 'EXA_API_KEY',
  },
  {
    slug: 'tavily',
    name: 'Tavily',
    source: 'vendor',
    publisher: 'Tavily',
    publisher_github: 'tavily-ai',
    github: 'tavily-ai/tavily-mcp',
    categories: ['search-web'],
    description: 'Search + extract pipeline tuned for agentic workflows. 1k free/mo.',
    use_case: 'Drop-in research agent — search, scrape, summarize in one call.',
    install: { npx: 'env TAVILY_API_KEY=tvly-... npx -y tavily-mcp' },
    transport: ['stdio'],
    requires_auth: true,
    auth_note: 'TAVILY_API_KEY (free tier)',
  },

  // ---------- DESIGN ----------
  {
    slug: 'figma',
    name: 'Figma',
    source: 'community',
    publisher: 'GLips',
    publisher_github: 'GLips',
    github: 'GLips/Figma-Context-MCP',
    docs: 'https://github.com/GLips/Figma-Context-MCP',
    categories: ['design'],
    description: 'Read Figma file structure, frames, components, styles into the agent.',
    use_case: 'Best agent → code design handoff in 2026. Cursor + Claude love it.',
    install: { npx: 'npx -y figma-developer-mcp --figma-api-key=YOUR_KEY' },
    transport: ['stdio'],
    requires_auth: true,
    auth_note: 'Figma personal access token',
  },
  {
    slug: 'canva',
    name: 'Canva',
    source: 'vendor',
    publisher: 'Canva',
    publisher_github: 'canva-public',
    github: 'canva-public/mcp',
    docs: 'https://www.canva.dev/docs/connect/mcp/',
    categories: ['design', 'media'],
    description: 'Generate, edit, export Canva designs from prompts.',
    use_case: 'Marketing agents that produce social-ready visuals.',
    install: { remote: 'https://mcp.canva.com/mcp' },
    transport: ['http'],
    requires_auth: true,
    auth_note: 'Canva OAuth',
  },

  // ---------- COMMUNICATION ----------
  {
    slug: 'discord',
    name: 'Discord',
    source: 'community',
    publisher: 'Barry Yip',
    publisher_github: 'barryyip0625',
    github: 'barryyip0625/mcp-discord',
    categories: ['communication'],
    description: 'Read channels, post messages, manage members on Discord guilds.',
    use_case: 'Community-ops agents that auto-welcome and triage tickets.',
    install: { npx: 'npx -y mcp-discord --token=...' },
    transport: ['stdio'],
    requires_auth: true,
    auth_note: 'Discord bot token',
  },
  {
    slug: 'gmail',
    name: 'Gmail',
    source: 'community',
    publisher: 'GongRzhe',
    publisher_github: 'GongRzhe',
    github: 'GongRzhe/Gmail-MCP-Server',
    categories: ['communication', 'productivity'],
    description: 'Read, search, send, label, draft emails in your Gmail account.',
    use_case: 'Inbox-zero agent that drafts replies you approve in one click.',
    install: { npx: 'npx -y @gongrzhe/server-gmail-autoauth-mcp' },
    transport: ['stdio'],
    requires_auth: true,
    auth_note: 'OAuth via Google Cloud project',
  },
  {
    slug: 'google-calendar',
    name: 'Google Calendar',
    source: 'community',
    publisher: 'takumi0706',
    publisher_github: 'takumi0706',
    github: 'takumi0706/google-calendar-mcp',
    categories: ['productivity'],
    description: 'List, create, update, delete events across your calendars.',
    use_case: 'Agent picks a slot that works for all attendees, books it.',
    install: { npx: 'npx -y google-calendar-mcp' },
    transport: ['stdio'],
    requires_auth: true,
    auth_note: 'OAuth via Google Cloud project',
  },
  {
    slug: 'twilio',
    name: 'Twilio',
    source: 'vendor',
    publisher: 'Twilio',
    publisher_github: 'twilio-labs',
    github: 'twilio-labs/mcp',
    categories: ['communication'],
    description: 'Send SMS / WhatsApp, place calls, fetch logs via Twilio API.',
    use_case: 'On-call agent that texts you when something breaks.',
    install: { npx: 'npx -y @twilio-alpha/mcp' },
    transport: ['stdio'],
    requires_auth: true,
    auth_note: 'Twilio account SID + auth token',
  },
  {
    slug: 'resend',
    name: 'Resend',
    source: 'vendor',
    publisher: 'Resend',
    publisher_github: 'resend',
    github: 'resend/mcp-send-email',
    categories: ['communication'],
    description: 'Send transactional + marketing email via Resend.',
    use_case: 'Agent drafts and sends release notes to your newsletter list.',
    install: { npx: 'npx -y mcp-send-email' },
    transport: ['stdio'],
    requires_auth: true,
    auth_note: 'RESEND_API_KEY',
  },
  {
    slug: 'intercom',
    name: 'Intercom',
    source: 'vendor',
    publisher: 'Intercom',
    publisher_github: 'intercom',
    github: 'intercom/intercom-mcp',
    categories: ['crm', 'communication'],
    description: 'Read conversations, push replies, manage contacts in Intercom.',
    use_case: 'Support-ops agent that triages and answers inbox first-response.',
    install: { remote: 'https://mcp.intercom.com/sse' },
    transport: ['sse'],
    requires_auth: true,
  },

  // ---------- PRODUCTIVITY ----------
  {
    slug: 'asana',
    name: 'Asana',
    source: 'community',
    publisher: 'roychri',
    publisher_github: 'roychri',
    github: 'roychri/mcp-server-asana',
    categories: ['productivity'],
    description: 'Tasks, projects, sections, comments — full Asana graph.',
    use_case: 'Sync engineering issues to a marketing-team Asana board.',
    install: { npx: 'npx -y @roychri/mcp-server-asana' },
    transport: ['stdio'],
    requires_auth: true,
  },
  {
    slug: 'clickup',
    name: 'ClickUp',
    source: 'community',
    publisher: 'Tahir Aziz',
    publisher_github: 'taazkareem',
    github: 'taazkareem/clickup-mcp-server',
    categories: ['productivity'],
    description: 'Tasks, lists, folders, custom fields across ClickUp workspaces.',
    use_case: 'Cross-team teams who live in ClickUp instead of Linear.',
    install: { npx: 'npx -y @taazkareem/clickup-mcp-server' },
    transport: ['stdio'],
    requires_auth: true,
  },
  {
    slug: 'todoist',
    name: 'Todoist',
    source: 'community',
    publisher: 'abhiz123',
    publisher_github: 'abhiz123',
    github: 'abhiz123/todoist-mcp-server',
    categories: ['productivity'],
    description: 'CRUD on tasks, projects, labels in Todoist.',
    use_case: 'Personal-productivity agents that maintain your real to-do list.',
    install: { npx: 'npx -y @abhiz123/todoist-mcp-server' },
    transport: ['stdio'],
    requires_auth: true,
  },
  {
    slug: 'obsidian',
    name: 'Obsidian',
    source: 'community',
    publisher: 'cyanheads',
    publisher_github: 'cyanheads',
    github: 'cyanheads/obsidian-mcp-server',
    categories: ['productivity', 'storage'],
    description: 'Read/write vault notes, search, follow links via Local REST API.',
    use_case: 'Second-brain agent that organizes your notes by topic.',
    install: { npx: 'npx -y obsidian-mcp-server' },
    transport: ['stdio'],
    requires_auth: true,
    auth_note: 'Obsidian Local REST API plugin + API key',
  },
  {
    slug: 'cal',
    name: 'Cal.com',
    source: 'community',
    publisher: 'Chuanming Liu',
    publisher_github: 'chuanmingliu',
    github: 'chuanmingliu/cal-mcp',
    categories: ['productivity'],
    description: 'Schedule meetings, manage event types, check availability via Cal.com API.',
    use_case: 'Agent books a sales demo into your real calendar with buffers.',
    install: { npx: 'npx -y cal-mcp' },
    transport: ['stdio'],
    requires_auth: true,
  },

  // ---------- E-COMMERCE ----------
  {
    slug: 'shopify',
    name: 'Shopify',
    source: 'vendor',
    publisher: 'Shopify',
    publisher_github: 'Shopify',
    github: 'Shopify/storefront-mcp',
    docs: 'https://shopify.dev/docs/api/usage/mcp',
    categories: ['ecommerce'],
    description: 'Storefront API — products, collections, carts, customers.',
    use_case: 'Shopping-assistant agents and store-ops automation.',
    install: { npx: 'npx -y @shopify/storefront-mcp' },
    transport: ['stdio'],
    requires_auth: true,
    auth_note: 'Shopify Storefront access token',
  },
  {
    slug: 'paypal',
    name: 'PayPal',
    source: 'vendor',
    publisher: 'PayPal',
    publisher_github: 'paypal',
    github: 'paypal/agent-toolkit',
    categories: ['payments'],
    description: 'Orders, refunds, payouts, subscriptions via PayPal v2 API.',
    use_case: 'For US-centric SaaS taking PayPal alongside Stripe.',
    install: { npx: 'npx -y @paypal/agent-toolkit' },
    transport: ['stdio'],
    requires_auth: true,
  },
  {
    slug: 'razorpay',
    name: 'Razorpay',
    source: 'community',
    publisher: 'Razorpay',
    publisher_github: 'razorpay',
    github: 'razorpay/razorpay-mcp-server',
    categories: ['payments'],
    description: 'INR-first payments — orders, subscriptions, refunds, payouts.',
    use_case: 'For India-focused SaaS already on Razorpay (like StackPicks).',
    install: { npx: 'npx -y @razorpay/mcp-server' },
    transport: ['stdio'],
    requires_auth: true,
    auth_note: 'Razorpay key ID + secret',
  },

  // ---------- CRM ----------
  {
    slug: 'hubspot',
    name: 'HubSpot',
    source: 'vendor',
    publisher: 'HubSpot',
    publisher_github: 'HubSpotDev',
    github: 'HubSpotDev/mcp-hubspot',
    categories: ['crm'],
    description: 'Contacts, deals, companies, tickets — full HubSpot CRM.',
    use_case: 'SDR agent updates deal stage from email replies.',
    install: { npx: 'npx -y @hubspot/mcp-server' },
    transport: ['stdio'],
    requires_auth: true,
  },
  {
    slug: 'salesforce',
    name: 'Salesforce',
    source: 'community',
    publisher: 'Salesforce MCP',
    publisher_github: 'salesforce-mcp',
    github: 'salesforce-mcp/salesforce-mcp',
    categories: ['crm'],
    description: 'SOQL queries, object CRUD, Apex run on any Salesforce org.',
    use_case: 'Enterprise-grade ops agents inside SFDC-driven companies.',
    install: { npx: 'npx -y salesforce-mcp' },
    transport: ['stdio'],
    requires_auth: true,
  },
  {
    slug: 'zendesk',
    name: 'Zendesk',
    source: 'community',
    publisher: 'reachsumit',
    publisher_github: 'reachsumit',
    github: 'reachsumit/zendesk-mcp-server',
    categories: ['crm', 'communication'],
    description: 'Tickets, users, organizations, macros, views.',
    use_case: 'Support-agent ops, ticket triage, customer history lookups.',
    install: { uvx: 'uvx zendesk-mcp-server' },
    transport: ['stdio'],
    requires_auth: true,
  },

  // ---------- ANALYTICS ----------
  {
    slug: 'posthog',
    name: 'PostHog',
    source: 'vendor',
    publisher: 'PostHog',
    publisher_github: 'PostHog',
    github: 'PostHog/mcp',
    docs: 'https://posthog.com/docs/cdp/mcp',
    categories: ['analytics'],
    description: 'Query events, build insights, create dashboards in PostHog.',
    use_case: 'Agent reads "what happened on launch day" from your funnel.',
    install: { remote: 'https://mcp.posthog.com/mcp' },
    transport: ['http', 'sse'],
    requires_auth: true,
    auth_note: 'PostHog personal API key',
  },
  {
    slug: 'mixpanel',
    name: 'Mixpanel',
    source: 'community',
    publisher: 'Mixpanel',
    publisher_github: 'mixpanel',
    github: 'mixpanel/mixpanel-mcp',
    categories: ['analytics'],
    description: 'JQL queries, funnel reports, user lookups on Mixpanel projects.',
    use_case: 'Same value as PostHog MCP for Mixpanel-shop teams.',
    install: { npx: 'npx -y @mixpanel/mcp-server' },
    transport: ['stdio'],
    requires_auth: true,
  },
  {
    slug: 'plausible',
    name: 'Plausible',
    source: 'community',
    publisher: 'Plausible',
    publisher_github: 'plausible',
    github: 'plausible/mcp-server',
    categories: ['analytics'],
    description: 'Pageviews, top sources, country breakdowns from Plausible Stats API.',
    use_case: 'Privacy-first analytics for agents.',
    install: { npx: 'npx -y plausible-mcp' },
    transport: ['stdio'],
    requires_auth: true,
  },

  // ---------- CLOUD / DEVOPS ----------
  {
    slug: 'vercel',
    name: 'Vercel',
    source: 'vendor',
    publisher: 'Vercel',
    publisher_github: 'vercel',
    github: 'vercel/mcp-adapter',
    categories: ['cloud', 'devops'],
    description: 'Deployments, projects, env vars, logs on Vercel.',
    use_case: 'Agent rolls back a bad deploy by id.',
    install: { remote: 'https://mcp.vercel.com/' },
    transport: ['http'],
    requires_auth: true,
    auth_note: 'Vercel OAuth',
  },
  {
    slug: 'railway',
    name: 'Railway',
    source: 'vendor',
    publisher: 'Railway',
    publisher_github: 'railwayapp',
    github: 'railwayapp/mcp',
    categories: ['cloud', 'devops'],
    description: 'Manage services, env vars, deployments, plugins on Railway.',
    use_case: 'Spin up a Postgres + worker stack from one agent prompt.',
    install: { npx: 'npx -y @railwayapp/mcp' },
    transport: ['stdio'],
    requires_auth: true,
    auth_note: 'Railway API token',
  },
  {
    slug: 'netlify',
    name: 'Netlify',
    source: 'vendor',
    publisher: 'Netlify',
    publisher_github: 'netlify',
    github: 'netlify/netlify-mcp',
    categories: ['cloud', 'devops'],
    description: 'Sites, deploys, env vars, redirects via the Netlify API.',
    use_case: 'Jamstack ops without leaving Cursor.',
    install: { npx: 'npx -y @netlify/mcp' },
    transport: ['stdio'],
    requires_auth: true,
  },
  {
    slug: 'fly',
    name: 'Fly.io',
    source: 'community',
    publisher: 'superfly',
    publisher_github: 'superfly',
    github: 'superfly/mcp-fly',
    categories: ['cloud', 'devops'],
    description: 'Apps, machines, volumes, scale on Fly.io.',
    use_case: 'Multi-region deploy ops by voice.',
    install: { npx: 'npx -y @superfly/mcp-fly' },
    transport: ['stdio'],
    requires_auth: true,
  },
  {
    slug: 'docker',
    name: 'Docker',
    source: 'community',
    publisher: 'quantgeekdev',
    publisher_github: 'quantgeekdev',
    github: 'quantgeekdev/docker-mcp',
    categories: ['devops', 'code-dev'],
    description: 'Build, run, stop, list containers + images via Docker socket.',
    use_case: 'Local dev agent that spins up a postgres container on demand.',
    install: { uvx: 'uvx docker-mcp' },
    transport: ['stdio'],
    requires_auth: false,
  },
  {
    slug: 'kubernetes',
    name: 'Kubernetes',
    source: 'community',
    publisher: 'Flux159',
    publisher_github: 'Flux159',
    github: 'Flux159/mcp-server-kubernetes',
    categories: ['devops'],
    description: 'kubectl-equivalent — pods, deployments, services, logs, exec.',
    use_case: 'On-call agent inspects pods during an incident.',
    install: { npx: 'npx -y mcp-server-kubernetes' },
    transport: ['stdio'],
    requires_auth: true,
    auth_note: 'Reads ~/.kube/config',
  },
  {
    slug: 'e2b',
    name: 'E2B Code Interpreter',
    source: 'vendor',
    publisher: 'E2B',
    publisher_github: 'e2b-dev',
    github: 'e2b-dev/mcp-server',
    categories: ['code-dev'],
    description: 'Spawn isolated cloud sandboxes to run Python / JS / shell code.',
    use_case: 'Agent runs untrusted code (data analysis, scripts) safely.',
    install: { npx: 'npx -y @e2b/mcp-server' },
    transport: ['stdio'],
    requires_auth: true,
    auth_note: 'E2B_API_KEY',
  },

  // ---------- AI / MEDIA ----------
  {
    slug: 'replicate',
    name: 'Replicate',
    source: 'community',
    publisher: 'mckaywrigley',
    publisher_github: 'mckaywrigley',
    github: 'mckaywrigley/replicate-mcp',
    categories: ['ai-llm', 'media'],
    description: 'Run any model on Replicate — image, video, audio, LLMs.',
    use_case: 'Cheapest way to give an agent access to thousands of OSS models.',
    install: { npx: 'npx -y replicate-mcp' },
    transport: ['stdio'],
    requires_auth: true,
    auth_note: 'REPLICATE_API_TOKEN',
  },
  {
    slug: 'elevenlabs',
    name: 'ElevenLabs',
    source: 'vendor',
    publisher: 'ElevenLabs',
    publisher_github: 'elevenlabs',
    github: 'elevenlabs/elevenlabs-mcp',
    categories: ['ai-llm', 'media'],
    description: 'TTS, voice cloning, dubbing, sound effects via ElevenLabs.',
    use_case: 'Agent that produces podcast intros / explainer voiceovers.',
    install: { uvx: 'uvx elevenlabs-mcp' },
    transport: ['stdio'],
    requires_auth: true,
    auth_note: 'ELEVENLABS_API_KEY',
  },
  {
    slug: 'fal',
    name: 'Fal.ai',
    source: 'community',
    publisher: 'raidendotai',
    publisher_github: 'raidendotai',
    github: 'raidendotai/fal-mcp',
    categories: ['ai-llm', 'media'],
    description: 'Run Flux, SDXL, video models on Fal\'s realtime infra.',
    use_case: 'Fastest hosted image gen — sub-second SDXL for chat agents.',
    install: { npx: 'npx -y fal-mcp' },
    transport: ['stdio'],
    requires_auth: true,
  },
  {
    slug: 'huggingface',
    name: 'Hugging Face',
    source: 'community',
    publisher: 'evalstate',
    publisher_github: 'evalstate',
    github: 'evalstate/mcp-hfspace',
    categories: ['ai-llm', 'media'],
    description: 'Call any public HF Space as an MCP tool — image, audio, text.',
    use_case: 'Try a model in 30s without writing inference code.',
    install: { npx: 'npx -y @llmindset/mcp-hfspace' },
    transport: ['stdio'],
    requires_auth: false,
  },
  {
    slug: 'openai',
    name: 'OpenAI',
    source: 'community',
    publisher: 'pierrebrunelle',
    publisher_github: 'pierrebrunelle',
    github: 'pierrebrunelle/mcp-server-openai',
    categories: ['ai-llm'],
    description: 'Run GPT, DALL-E, embedding calls via OpenAI API.',
    use_case: 'Sub-agent pattern — let Claude call OpenAI for a second opinion.',
    install: { uvx: 'uvx mcp-server-openai' },
    transport: ['stdio'],
    requires_auth: true,
    auth_note: 'OPENAI_API_KEY',
  },
  {
    slug: 'langfuse',
    name: 'Langfuse',
    source: 'vendor',
    publisher: 'Langfuse',
    publisher_github: 'langfuse',
    github: 'langfuse/mcp-server-langfuse',
    categories: ['ai-llm', 'analytics'],
    description: 'Trace, score, and debug LLM workflows logged in Langfuse.',
    use_case: 'Build observability into agent loops — find slow / expensive spans.',
    install: { npx: 'npx -y @langfuse/mcp-server' },
    transport: ['stdio'],
    requires_auth: true,
  },

  // ---------- CODE / DEV TOOLS ----------
  {
    slug: 'sentry-issues',
    name: 'GitHub Actions',
    source: 'community',
    publisher: 'ko1ynnky',
    publisher_github: 'ko1ynnky',
    github: 'ko1ynnky/github-actions-mcp-server',
    categories: ['code-dev', 'devops'],
    description: 'Run, cancel, inspect GitHub Actions workflows and runs.',
    use_case: 'Agent retries a flaky build instead of you re-clicking.',
    install: { npx: 'npx -y github-actions-mcp-server' },
    transport: ['stdio'],
    requires_auth: true,
  },

  // ---------- MEDIA / SOCIAL ----------
  {
    slug: 'youtube',
    name: 'YouTube',
    source: 'community',
    publisher: 'icraft2170',
    publisher_github: 'icraft2170',
    github: 'icraft2170/youtube-data-mcp-server',
    categories: ['media', 'search-web'],
    description: 'Search videos, transcripts, channel stats via YouTube Data API.',
    use_case: 'Research agent that pulls + summarizes long-form video.',
    install: { npx: 'npx -y youtube-data-mcp-server' },
    transport: ['stdio'],
    requires_auth: true,
  },
  {
    slug: 'reddit',
    name: 'Reddit',
    source: 'community',
    publisher: 'jordanburke',
    publisher_github: 'jordanburke',
    github: 'jordanburke/reddit-mcp-server',
    categories: ['communication', 'search-web'],
    description: 'Search subs, read threads, post comments via Reddit API.',
    use_case: 'Marketing agents listening for product mentions.',
    install: { npx: 'npx -y reddit-mcp-server' },
    transport: ['stdio'],
    requires_auth: true,
  },
  {
    slug: 'x-twitter',
    name: 'X (Twitter)',
    source: 'community',
    publisher: 'vidhupv',
    publisher_github: 'vidhupv',
    github: 'vidhupv/x-mcp',
    categories: ['communication', 'media'],
    description: 'Post tweets, search, read DMs via the X API v2.',
    use_case: 'Auto-publish release notes; archive your own threads.',
    install: { uvx: 'uvx x-mcp' },
    transport: ['stdio'],
    requires_auth: true,
    auth_note: 'X API v2 bearer token',
  },
  {
    slug: 'spotify',
    name: 'Spotify',
    source: 'community',
    publisher: 'varunneal',
    publisher_github: 'varunneal',
    github: 'varunneal/spotify-mcp',
    categories: ['media'],
    description: 'Control playback, search tracks, manage playlists on your account.',
    use_case: 'Mood-based playlist agent. Fun > useful.',
    install: { uvx: 'uvx spotify-mcp' },
    transport: ['stdio'],
    requires_auth: true,
  },

  // ---------- STORAGE ----------
  {
    slug: 'aws-s3',
    name: 'AWS S3',
    source: 'community',
    publisher: 'AWS Labs',
    publisher_github: 'awslabs',
    github: 'awslabs/mcp',
    categories: ['storage', 'cloud'],
    description: 'List, get, put, delete S3 objects and buckets.',
    use_case: 'Agent uploads generated assets to S3 + returns the public URL.',
    install: { uvx: 'uvx awslabs.s3-mcp' },
    transport: ['stdio'],
    requires_auth: true,
    auth_note: 'AWS credentials chain',
  },
  {
    slug: 'dropbox',
    name: 'Dropbox',
    source: 'community',
    publisher: 'baryhuang',
    publisher_github: 'baryhuang',
    github: 'baryhuang/mcp-server-dropbox',
    categories: ['storage'],
    description: 'List, read, upload, search Dropbox files.',
    use_case: 'For teams that live in Dropbox instead of Drive.',
    install: { npx: 'npx -y mcp-server-dropbox' },
    transport: ['stdio'],
    requires_auth: true,
  },

  // ---------- SECURITY ----------
  {
    slug: 'vault',
    name: 'HashiCorp Vault',
    source: 'community',
    publisher: 'ashgw',
    publisher_github: 'ashgw',
    github: 'ashgw/vault-mcp',
    categories: ['security', 'devops'],
    description: 'Read / write secrets in a Vault server with policy scoping.',
    use_case: 'Agent fetches DB password from Vault instead of env files.',
    install: { npx: 'npx -y vault-mcp' },
    transport: ['stdio'],
    requires_auth: true,
    auth_note: 'Vault token',
  },
  {
    slug: '1password',
    name: '1Password',
    source: 'vendor',
    publisher: '1Password',
    publisher_github: '1Password',
    github: '1Password/mcp-server-1password',
    categories: ['security'],
    description: 'Read items / secrets from a 1Password vault via Service Account.',
    use_case: 'Same as Vault but for teams already on 1Password Business.',
    install: { npx: 'npx -y @1password/mcp-server-1password' },
    transport: ['stdio'],
    requires_auth: true,
    auth_note: '1Password Service Account token',
  },

  // ---------- BUNDLES / OTHER ----------
  {
    slug: 'wordpress',
    name: 'WordPress',
    source: 'vendor',
    publisher: 'Automattic',
    publisher_github: 'Automattic',
    github: 'Automattic/mcp-wordpress-remote',
    categories: ['storage', 'productivity'],
    description: 'Create posts, manage media, list comments via WP REST API.',
    use_case: 'Auto-publish blog posts from agent-generated drafts.',
    install: { npx: 'npx -y @automattic/mcp-wordpress-remote' },
    transport: ['stdio'],
    requires_auth: true,
  },
  {
    slug: 'notion-database',
    name: 'Zapier MCP',
    source: 'vendor',
    publisher: 'Zapier',
    publisher_github: 'zapier',
    docs: 'https://mcp.zapier.com',
    categories: ['productivity'],
    description: '8,000+ apps as tools via your existing Zapier Zaps.',
    use_case: 'Fastest way to give an agent access to your full SaaS stack.',
    install: { remote: 'https://mcp.zapier.com/api/mcp/mcp' },
    transport: ['http', 'sse'],
    requires_auth: true,
    auth_note: 'Zapier OAuth + per-action allow-list',
  },
];

export const MCP_BY_SLUG: Record<string, MCPServer> = Object.fromEntries(
  MCP_SERVERS.map((s) => [s.slug, s]),
);

export function getServersByCategory(slug: MCPCategory): MCPServer[] {
  return MCP_SERVERS.filter((s) => s.categories.includes(slug));
}
