/**
 * "Open-source alternative to X" pages — the highest-volume keyword class
 * we don't currently target. Each page captures specific "open source alternative to <SaaS>" queries.
 *
 * Each alternative is inline-defined here so we don't need to seed all the new repos
 * into the main DB — these pages can stand alone.
 */

export interface OssPick {
  full_name: string;             // e.g. "n8n-io/n8n"
  short_name: string;            // Display name
  curator_take: string;          // 80-160 words
  use_this_if: string;
  skip_if: string;
  homepage?: string;
  license?: string;
  stars_approx?: number;         // For social proof — approximate ok
  self_hosted: boolean;
}

export interface AlternativePage {
  slug: string;                  // URL slug, e.g. "notion"
  saas_name: string;             // Display name of the SaaS being replaced
  query: string;                 // Target search query
  monthly_searches: number;      // Estimated
  category: string;              // Grouping
  saas_blurb: string;            // 1-2 sentence description of what the SaaS is + why people want OSS
  picks: OssPick[];              // 3-5 OSS alternatives, ordered best to worst
}

export const ALTERNATIVES: AlternativePage[] = [
  // ─── HIGHEST VOLUME ────────────────────────────────────────────────
  {
    slug: 'chatgpt',
    saas_name: 'ChatGPT',
    query: 'open source alternative to chatgpt',
    monthly_searches: 8100,
    category: 'AI',
    saas_blurb: 'ChatGPT is OpenAI\'s consumer chatbot. People want open-source alternatives for privacy, offline use, custom fine-tuning, and to avoid the $20/mo subscription.',
    picks: [
      {
        full_name: 'ollama/ollama',
        short_name: 'Ollama',
        curator_take: 'Ollama is the easiest way to run Llama 3.3, Qwen 2.5, DeepSeek-R1, Mistral, and 100+ other models locally. One install, one command (`ollama run llama3.3`), works on Mac/Linux/Windows. Pairs with any chat UI (OpenWebUI is the most popular). For privacy-sensitive work or building products that need local inference, this is the foundation.',
        use_this_if: 'You want fully local LLM inference, you need privacy guarantees, or you want to avoid API costs while developing AI products.',
        skip_if: 'You need GPT-4-class reasoning on consumer hardware — open models are getting closer but still trail proprietary frontier models on hard reasoning tasks.',
        license: 'MIT',
        stars_approx: 110000,
        self_hosted: true,
      },
      {
        full_name: 'open-webui/open-webui',
        short_name: 'OpenWebUI',
        curator_take: 'OpenWebUI gives you a ChatGPT-clone interface that runs against your local Ollama instance (or any OpenAI-compatible endpoint). Multi-user, RAG over documents, model switcher, conversation history. Self-host with Docker in 5 minutes. Combined with Ollama, this is the full ChatGPT replacement stack.',
        use_this_if: 'You\'re running Ollama and want a beautiful UI instead of the CLI. Or you want to give your team a private ChatGPT-like experience.',
        skip_if: 'You only need a single-user setup — the Ollama desktop apps are simpler.',
        license: 'MIT',
        stars_approx: 65000,
        self_hosted: true,
      },
      {
        full_name: 'huggingface/transformers',
        short_name: 'Hugging Face Transformers',
        curator_take: 'The Python library that runs every modern open-source LLM. Lower-level than Ollama — you load models manually, manage GPU memory yourself. Pick this if you\'re building a custom AI product, fine-tuning models, or running production inference at scale.',
        use_this_if: 'You\'re building production AI products, doing research, or need fine-tuning capabilities.',
        skip_if: 'You just want to chat with an LLM — Ollama is simpler.',
        license: 'Apache 2.0',
        stars_approx: 135000,
        self_hosted: true,
      },
    ],
  },

  {
    slug: 'notion',
    saas_name: 'Notion',
    query: 'open source alternative to notion',
    monthly_searches: 6600,
    category: 'Productivity',
    saas_blurb: 'Notion is the leading "all-in-one workspace" — docs, wikis, databases, projects. People want OSS alternatives for self-hosting, privacy, no vendor lock-in, and to escape the $10/user/month team plans.',
    picks: [
      {
        full_name: 'AppFlowy-IO/AppFlowy',
        short_name: 'AppFlowy',
        curator_take: 'AppFlowy is the closest Notion clone in 2026 — same block-based editor, same database views, same drag-and-drop. Built in Rust + Flutter so it\'s fast on every platform. Cloud and self-host both supported. The team has been shipping aggressively for 3 years; this is the OSS Notion of choice.',
        use_this_if: 'You want a near 1:1 Notion replacement with self-hosting and AI features baked in.',
        skip_if: 'Your team is deeply embedded in Notion templates and integrations — migration is real work.',
        license: 'AGPL-3.0',
        stars_approx: 60000,
        self_hosted: true,
      },
      {
        full_name: 'toeverything/AFFiNE',
        short_name: 'AFFiNE',
        curator_take: 'AFFiNE merges Notion\'s block editor with Miro\'s infinite canvas. Same page can be a doc, a table, or a whiteboard. Local-first by default, sync via your own backend. Best for design + dev teams who want both linear docs and visual workspaces in one tool.',
        use_this_if: 'You need both Notion-style docs AND Miro-style whiteboards in one tool.',
        skip_if: 'You only need docs/databases — AppFlowy is simpler.',
        license: 'MIT',
        stars_approx: 45000,
        self_hosted: true,
      },
      {
        full_name: 'logseq/logseq',
        short_name: 'Logseq',
        curator_take: 'Logseq is the Roam Research / Obsidian-style outliner — markdown files, bidirectional links, daily journaling, graph view. Not a Notion clone but the right pick if your primary use is personal knowledge management (PKM) over team databases.',
        use_this_if: 'You want personal knowledge management with markdown files you own.',
        skip_if: 'You need team databases and structured project tracking.',
        license: 'AGPL-3.0',
        stars_approx: 35000,
        self_hosted: true,
      },
      {
        full_name: 'outline/outline',
        short_name: 'Outline',
        curator_take: 'Outline is the team wiki / docs replacement — clean Markdown editor, hierarchical organization, slash commands. No database views (unlike Notion). Best for documentation-heavy teams who don\'t need Notion\'s database features.',
        use_this_if: 'Your team needs a clean wiki/docs tool without the database complexity.',
        skip_if: 'You need database views — pick AppFlowy.',
        license: 'BSL 1.1',
        stars_approx: 30000,
        self_hosted: true,
      },
    ],
  },

  {
    slug: 'figma',
    saas_name: 'Figma',
    query: 'open source alternative to figma',
    monthly_searches: 5400,
    category: 'Design',
    saas_blurb: 'Figma is the dominant collaborative design tool. After Adobe\'s attempted acquisition, many teams want OSS alternatives for self-hosting, file portability, and to avoid future pricing changes.',
    picks: [
      {
        full_name: 'penpot/penpot',
        short_name: 'Penpot',
        curator_take: 'Penpot is the only serious open-source Figma alternative in 2026. Full vector editing, components, prototyping, design system support, real-time collaboration. Self-hostable with Docker. SVG-native files (Figma uses a proprietary format). Used by Mozilla, Wikipedia, and other public-sector teams that need OSS by mandate.',
        use_this_if: 'You need real-time collaborative design with SVG-native portability, especially if you\'re in public sector / EU GDPR-sensitive industry.',
        skip_if: 'Your team has 6+ years of Figma muscle memory — migration is months of work.',
        license: 'MPL-2.0',
        stars_approx: 36000,
        self_hosted: true,
      },
      {
        full_name: 'excalidraw/excalidraw',
        short_name: 'Excalidraw',
        curator_take: 'Excalidraw is hand-drawn-style whiteboarding — not a Figma replacement but the right tool for design sketches, architecture diagrams, and quick ideation. End-to-end encrypted rooms. Beloved by engineers for "back of napkin" diagrams.',
        use_this_if: 'You need quick sketches, system diagrams, or whiteboarding (not pixel-perfect mockups).',
        skip_if: 'You need component-based design with design tokens — pick Penpot.',
        license: 'MIT',
        stars_approx: 90000,
        self_hosted: true,
      },
      {
        full_name: 'tldraw/tldraw',
        short_name: 'tldraw',
        curator_take: 'tldraw is a modern, polished whiteboard with AI-powered features (sketch-to-app). Library you can embed in your own product. Same niche as Excalidraw but with a more "designer-friendly" feel and better extensibility.',
        use_this_if: 'You want to embed whiteboarding in your own SaaS product.',
        skip_if: 'You need a standalone tool — Excalidraw is simpler.',
        license: 'MIT (with restrictions)',
        stars_approx: 36000,
        self_hosted: true,
      },
    ],
  },

  {
    slug: 'airtable',
    saas_name: 'Airtable',
    query: 'open source alternative to airtable',
    monthly_searches: 4500,
    category: 'No-code databases',
    saas_blurb: 'Airtable popularized spreadsheet-database hybrids. Open-source alternatives exist for self-hosting, removing per-user pricing, and avoiding the workflow lock-in.',
    picks: [
      {
        full_name: 'nocodb/nocodb',
        short_name: 'NocoDB',
        curator_take: 'NocoDB is the closest Airtable clone. Connects to MySQL/Postgres/SQLite/MSSQL/Snowflake — turns any database into an Airtable-like UI with grid/gallery/kanban/form views, automations, and API access. Self-host with Docker. The smartest pick if you have existing relational data you want to make spreadsheet-accessible.',
        use_this_if: 'You have existing SQL data you want to expose to non-technical users as Airtable-style views.',
        skip_if: 'You\'re starting from scratch with no existing DB — Baserow is simpler.',
        license: 'AGPL-3.0',
        stars_approx: 55000,
        self_hosted: true,
      },
      {
        full_name: 'bram2w/baserow',
        short_name: 'Baserow',
        curator_take: 'Baserow is the prettiest no-code database — Airtable-style UI with formulas, links between tables, automations, and a strong free SaaS tier (plus full self-host). Best DX for non-technical users.',
        use_this_if: 'Your team includes non-developers who need to manage data without SQL.',
        skip_if: 'You need to wrap an existing database — pick NocoDB.',
        license: 'MIT',
        stars_approx: 18000,
        self_hosted: true,
      },
      {
        full_name: 'directus/directus',
        short_name: 'Directus',
        curator_take: 'Directus wraps any SQL database as a flexible no-code admin + REST/GraphQL API. More backend-y than Airtable — but if you need a CMS + a no-code DB UI in one tool, this is the pick.',
        use_this_if: 'You need a CMS-like layer over your existing database plus an API to query it.',
        skip_if: 'You want spreadsheet aesthetics — NocoDB or Baserow.',
        license: 'BSL 1.1',
        stars_approx: 30000,
        self_hosted: true,
      },
    ],
  },

  {
    slug: 'slack',
    saas_name: 'Slack',
    query: 'open source alternative to slack',
    monthly_searches: 3300,
    category: 'Team chat',
    saas_blurb: 'Slack is the team chat default. OSS alternatives matter for self-hosting (privacy/compliance), avoiding per-user pricing, and keeping data on-prem in regulated industries.',
    picks: [
      {
        full_name: 'mattermost/mattermost',
        short_name: 'Mattermost',
        curator_take: 'Mattermost is the closest Slack clone — channels, DMs, threads, integrations, mobile apps. Used by DoD, EU Parliament, regulated enterprises. Self-host in Docker, K8s-ready. Enterprise SSO/SAML/LDAP in the free version.',
        use_this_if: 'You need a Slack replacement for compliance/sovereignty reasons. Or you want to own your team\'s data.',
        skip_if: 'Your team is small and Slack free tier works fine — self-hosting has real overhead.',
        license: 'MIT + Enterprise modules',
        stars_approx: 30000,
        self_hosted: true,
      },
      {
        full_name: 'RocketChat/Rocket.Chat',
        short_name: 'Rocket.Chat',
        curator_take: 'Rocket.Chat is similar to Mattermost but adds live chat / customer support widgets (so you can talk to customers AND internal team in one tool). Strong for hybrid use cases. More feature-rich but heavier.',
        use_this_if: 'You need internal team chat + external customer support chat in one tool.',
        skip_if: 'You only need internal team chat — Mattermost is leaner.',
        license: 'MIT',
        stars_approx: 41000,
        self_hosted: true,
      },
      {
        full_name: 'element-hq/element-web',
        short_name: 'Element (Matrix)',
        curator_take: 'Element is the reference client for the Matrix protocol — federated, end-to-end encrypted by default, used by the French government and many security-sensitive orgs. Different paradigm (federated like email, not centralized like Slack).',
        use_this_if: 'You need end-to-end encryption + federation across orgs (not just internal teams).',
        skip_if: 'You want Slack-clone simplicity — Mattermost is closer to that.',
        license: 'AGPL-3.0',
        stars_approx: 11000,
        self_hosted: true,
      },
    ],
  },

  {
    slug: 'zapier',
    saas_name: 'Zapier',
    query: 'open source alternative to zapier',
    monthly_searches: 2900,
    category: 'Automation',
    saas_blurb: 'Zapier popularized "if-this-then-that" automation between SaaS apps. OSS alternatives let you self-host, avoid per-run pricing, and use unlimited steps.',
    picks: [
      {
        full_name: 'n8n-io/n8n',
        short_name: 'n8n',
        curator_take: 'n8n is the dominant Zapier alternative. 400+ integrations, visual node editor, code nodes (JS/Python), AI nodes (LangChain, OpenAI), self-host with Docker. Strong commercial support + cloud option. The clear pick for serious automation.',
        use_this_if: 'You need a powerful Zapier replacement with code-level flexibility and AI integration.',
        skip_if: 'You only need 2-3 simple automations — Zapier free tier is easier.',
        license: 'Sustainable Use License',
        stars_approx: 75000,
        self_hosted: true,
      },
      {
        full_name: 'activepieces/activepieces',
        short_name: 'Activepieces',
        curator_take: 'Activepieces is the cleaner, simpler n8n. Lighter UI, easier to self-host, growing integration library. Best for teams that want n8n\'s feel but with less complexity.',
        use_this_if: 'You want a simpler, prettier n8n. Or you\'re on the fence between n8n and Make.',
        skip_if: 'You need maximum integration coverage — n8n still leads on count.',
        license: 'MIT + Commons Clause',
        stars_approx: 12000,
        self_hosted: true,
      },
      {
        full_name: 'huginn/huginn',
        short_name: 'Huginn',
        curator_take: 'Huginn is the OG (started in 2013). Less polished UI than n8n but battle-tested, no licensing weirdness, fully open-source. Best for developers who want raw flexibility over UI polish.',
        use_this_if: 'You want a 100%-open-source-no-commercial-strings automation tool.',
        skip_if: 'You want a modern UI — n8n is way prettier.',
        license: 'MIT',
        stars_approx: 45000,
        self_hosted: true,
      },
    ],
  },

  {
    slug: 'discord',
    saas_name: 'Discord',
    query: 'open source alternative to discord',
    monthly_searches: 2400,
    category: 'Community chat',
    saas_blurb: 'Discord dominates community chat but locks you in. OSS alternatives matter for community ownership, no ads/data harvesting, and self-hosting for privacy-sensitive groups.',
    picks: [
      {
        full_name: 'revoltchat/revolt',
        short_name: 'Revolt',
        curator_take: 'Revolt is the closest Discord clone — voice channels, custom emoji, bots, mobile apps. Modern UI, actively developed, fully open-source. Self-host or use the hosted instance.',
        use_this_if: 'You want Discord features for your community without the corporate ownership.',
        skip_if: 'Your community is already on Discord — migration is brutal for established communities.',
        license: 'AGPL-3.0',
        stars_approx: 5500,
        self_hosted: true,
      },
      {
        full_name: 'element-hq/element-web',
        short_name: 'Element (Matrix)',
        curator_take: 'Federated, encrypted alternative. Different model than Discord (rooms, not servers) but the right pick for privacy-first communities and organizations that need E2EE.',
        use_this_if: 'You need end-to-end encryption or federation across orgs.',
        skip_if: 'Your community wants Discord-clone UX — Revolt is closer.',
        license: 'AGPL-3.0',
        stars_approx: 11000,
        self_hosted: true,
      },
    ],
  },

  {
    slug: 'canva',
    saas_name: 'Canva',
    query: 'open source alternative to canva',
    monthly_searches: 2200,
    category: 'Design',
    saas_blurb: 'Canva is the dominant easy-design tool for non-designers (social posts, presentations, marketing materials). OSS alternatives are scarce but exist.',
    picks: [
      {
        full_name: 'penpot/penpot',
        short_name: 'Penpot',
        curator_take: 'Penpot leans more designer/Figma than Canva — but it includes templates, libraries, and is more capable than Canva for serious design work. If your team has any design literacy, Penpot is better. If they\'re marketers who want drag-and-drop posters, Penpot is overkill.',
        use_this_if: 'Your team includes designers who currently use Canva because it\'s easy.',
        skip_if: 'You need a true Canva-clone with social-media-post templates and zero design knowledge.',
        license: 'MPL-2.0',
        stars_approx: 36000,
        self_hosted: true,
      },
      {
        full_name: 'photopea/photopea-source',
        short_name: 'Photopea',
        curator_take: 'Photopea is the open-source Photoshop in your browser. Different niche than Canva but works for raster image editing. Best for editing photos, adding text, creating raster graphics — not template-based design.',
        use_this_if: 'You need Photoshop-style image editing in the browser without paying Adobe.',
        skip_if: 'You need template-based marketing design — Penpot is closer.',
        license: 'Various',
        stars_approx: 7500,
        self_hosted: false,
      },
    ],
  },

  {
    slug: 'github',
    saas_name: 'GitHub',
    query: 'open source alternative to github',
    monthly_searches: 2000,
    category: 'Code hosting',
    saas_blurb: 'GitHub is owned by Microsoft. Open-source alternatives exist for self-hosting your code (sovereignty, privacy) and to avoid MS lock-in.',
    picks: [
      {
        full_name: 'go-gitea/gitea',
        short_name: 'Gitea',
        curator_take: 'Gitea is the lightweight self-host GitHub clone. Issues, PRs, wiki, releases, packages, actions. Single Go binary, runs anywhere, sips RAM. The dominant pick for personal/team self-hosted git.',
        use_this_if: 'You want a self-hosted GitHub for your team without the resource overhead of GitLab.',
        skip_if: 'You need CI/CD at GitLab\'s scale or built-in DevSecOps features.',
        license: 'MIT',
        stars_approx: 47000,
        self_hosted: true,
      },
      {
        full_name: 'forgejo/forgejo',
        short_name: 'Forgejo',
        curator_take: 'Forgejo is the community fork of Gitea (forked over governance concerns). 99% feature-compatible. Pick Forgejo if you care about the more open governance model; pick Gitea if you want the larger ecosystem.',
        use_this_if: 'You care about transparent, community-led governance for your self-hosted git.',
        skip_if: 'You want the larger ecosystem — Gitea has more plugins/themes.',
        license: 'MIT',
        stars_approx: 4000,
        self_hosted: true,
      },
      {
        full_name: 'gitlab-org/gitlab',
        short_name: 'GitLab CE',
        curator_take: 'GitLab Community Edition is the heaviest pick — full DevOps platform with CI/CD, container registry, security scanning, monitoring. Run it if you need the whole stack; otherwise it\'s overkill.',
        use_this_if: 'You need GitLab\'s full DevOps suite (CI/CD, registries, monitoring) and have ops capacity to run it.',
        skip_if: 'You just need git hosting — Gitea is 100× lighter.',
        license: 'MIT',
        stars_approx: 24000,
        self_hosted: true,
      },
    ],
  },

  {
    slug: 'typeform',
    saas_name: 'Typeform',
    query: 'open source alternative to typeform',
    monthly_searches: 1800,
    category: 'Forms / Surveys',
    saas_blurb: 'Typeform makes beautiful conversational forms. OSS alternatives let you self-host (no per-response pricing), keep response data private, and brand fully.',
    picks: [
      {
        full_name: 'formbricks/formbricks',
        short_name: 'Formbricks',
        curator_take: 'Formbricks is the modern OSS Typeform — beautiful forms, conditional logic, embeds, in-app surveys, NPS, response analytics. Self-host with Docker or use cloud. Best DX of any OSS form builder in 2026.',
        use_this_if: 'You need beautiful self-hosted forms with full analytics and no response limits.',
        skip_if: 'You just need a 5-question contact form — Tally\'s free tier is simpler.',
        license: 'AGPL-3.0',
        stars_approx: 9000,
        self_hosted: true,
      },
      {
        full_name: 'documenso/documenso',
        short_name: 'Documenso',
        curator_take: 'Not a form tool exactly — Documenso is the open-source DocuSign for digital signatures. Mentioned here because Typeform users often graduate to needing signatures (NDAs, contracts) and Documenso pairs perfectly.',
        use_this_if: 'Your forms collect signatures — Typeform doesn\'t do this well.',
        skip_if: 'You just need basic forms — Formbricks is the answer.',
        license: 'AGPL-3.0',
        stars_approx: 9000,
        self_hosted: true,
      },
    ],
  },

  {
    slug: 'dropbox',
    saas_name: 'Dropbox',
    query: 'open source alternative to dropbox',
    monthly_searches: 1500,
    category: 'File sync / storage',
    saas_blurb: 'Dropbox/Google Drive/OneDrive all dominate file sync. OSS alternatives let you keep your files on your own servers — critical for privacy, EU GDPR, sovereignty.',
    picks: [
      {
        full_name: 'nextcloud/server',
        short_name: 'Nextcloud',
        curator_take: 'Nextcloud is the comprehensive self-hosted suite — files, calendars, contacts, video chat, office suite (with Collabora/OnlyOffice), photos, all on your own server. Used by EU governments. The dominant OSS pick.',
        use_this_if: 'You want a comprehensive self-hosted productivity suite that replaces Dropbox + Google Workspace.',
        skip_if: 'You only need file sync without the office/calendar bloat.',
        license: 'AGPL-3.0',
        stars_approx: 28000,
        self_hosted: true,
      },
      {
        full_name: 'syncthing/syncthing',
        short_name: 'Syncthing',
        curator_take: 'Syncthing is peer-to-peer file sync. No central server, no cloud — devices sync directly. Best for personal sync between your own devices (laptop ↔ desktop ↔ phone).',
        use_this_if: 'You want device-to-device sync without any cloud middleman.',
        skip_if: 'You need shared team folders or web access — Nextcloud is the answer.',
        license: 'MPL-2.0',
        stars_approx: 65000,
        self_hosted: true,
      },
      {
        full_name: 'seafile/seafile',
        short_name: 'Seafile',
        curator_take: 'Seafile is faster and lighter than Nextcloud — pure file sync without the office-suite bloat. Better for teams that just need shared folders + version history.',
        use_this_if: 'You want fast, lean self-hosted file sync without the kitchen-sink approach.',
        skip_if: 'You need calendars, office docs, video chat too — Nextcloud is more complete.',
        license: 'GPL-2.0',
        stars_approx: 12500,
        self_hosted: true,
      },
    ],
  },

  {
    slug: 'mailchimp',
    saas_name: 'Mailchimp',
    query: 'open source alternative to mailchimp',
    monthly_searches: 1500,
    category: 'Email marketing',
    saas_blurb: 'Mailchimp is the popular email marketing tool. OSS alternatives let you self-host and pay only for sending infrastructure (e.g. SES at ~$0.10 per 1000 emails) instead of per-subscriber.',
    picks: [
      {
        full_name: 'knadh/listmonk',
        short_name: 'Listmonk',
        curator_take: 'Listmonk is the dominant OSS email marketing tool. Newsletters, campaigns, segmentation, list management, analytics. Single Go binary + Postgres. Pair with AWS SES or Mailgun for sending. Costs ~$5/mo for 100k subscribers vs. Mailchimp\'s $300+.',
        use_this_if: 'You have 1k+ subscribers and want to escape per-subscriber pricing.',
        skip_if: 'You\'re under 500 subscribers — Mailchimp free tier is easier.',
        license: 'AGPL-3.0',
        stars_approx: 17000,
        self_hosted: true,
      },
      {
        full_name: 'keila-io/keila',
        short_name: 'Keila',
        curator_take: 'Keila is the newer, Elixir-based alternative to Listmonk. Cleaner UI, simpler setup. Smaller community but actively developed.',
        use_this_if: 'You prefer a cleaner UI and don\'t need Listmonk\'s breadth of features.',
        skip_if: 'You need a battle-tested tool with bigger community — Listmonk is more mature.',
        license: 'AGPL-3.0',
        stars_approx: 1200,
        self_hosted: true,
      },
    ],
  },

  {
    slug: 'calendly',
    saas_name: 'Calendly',
    query: 'open source alternative to calendly',
    monthly_searches: 900,
    category: 'Scheduling',
    saas_blurb: 'Calendly is the dominant scheduling tool. Open-source alternatives let you self-host, brand fully, and skip per-user pricing.',
    picks: [
      {
        full_name: 'calcom/cal.diy',
        short_name: 'Cal.com',
        curator_take: 'Cal.com is the Calendly killer. Open-source, self-host or use the cloud (free tier). All features Calendly has, plus team scheduling, workflows, payments, routing forms. Built on Next.js + Postgres. The dominant pick.',
        use_this_if: 'You want Calendly\'s functionality with full ownership and no per-user pricing.',
        skip_if: 'You only need solo scheduling and don\'t want to self-host — Cal.com\'s cloud free tier is the move.',
        license: 'AGPL-3.0',
        stars_approx: 35000,
        self_hosted: true,
      },
    ],
  },

  {
    slug: 'google-analytics',
    saas_name: 'Google Analytics',
    query: 'open source alternative to google analytics',
    monthly_searches: 4400,
    category: 'Analytics',
    saas_blurb: 'Google Analytics is free but invasive (tracks users with cookies, requires GDPR cookie banner, slows your site). OSS alternatives are privacy-first, GDPR-safe, and faster.',
    picks: [
      {
        full_name: 'plausible/analytics',
        short_name: 'Plausible',
        curator_take: 'Plausible is the privacy-first, cookie-free analytics that GDPR/DPDP-conscious sites use. 1KB script, no cookies, no consent banner needed. Self-host (free) or cloud ($9/mo). The default pick for new sites in 2026.',
        use_this_if: 'You want simple, fast, GDPR-safe analytics with no cookie banner.',
        skip_if: 'You need session replay, funnels, or product analytics — PostHog is the answer.',
        license: 'AGPL-3.0',
        stars_approx: 21500,
        self_hosted: true,
      },
      {
        full_name: 'umami-software/umami',
        short_name: 'Umami',
        curator_take: 'Umami is fully OSS Plausible — same privacy-first model, but completely free if you self-host. Slightly less polished UI but battle-tested. The pick if you want zero recurring cost.',
        use_this_if: 'You want Plausible-style analytics but fully self-hosted for free.',
        skip_if: 'You want managed cloud — Plausible\'s cloud is worth $9/mo for the convenience.',
        license: 'MIT',
        stars_approx: 26000,
        self_hosted: true,
      },
      {
        full_name: 'PostHog/posthog',
        short_name: 'PostHog',
        curator_take: 'PostHog is full product analytics — page views, funnels, retention, session replay, feature flags, A/B testing, in-app surveys, error tracking. Way more than GA. Self-host or use the very generous cloud free tier.',
        use_this_if: 'You\'re building a SaaS and need product analytics (not just marketing site stats).',
        skip_if: 'You only need page-view counting — PostHog is overkill.',
        license: 'MIT',
        stars_approx: 23000,
        self_hosted: true,
      },
    ],
  },

  // ─── DEV TOOLS ─────────────────────────────────────────────────────
  {
    slug: 'postman',
    saas_name: 'Postman',
    query: 'open source alternative to postman',
    monthly_searches: 4400,
    category: 'API Testing',
    saas_blurb: 'Postman is the dominant API testing client but went cloud-only in 2024 — forcing teams onto its servers and breaking offline workflows. The open-source alternatives put your collections back in git, work offline, and skip the per-user pricing.',
    picks: [
      {
        full_name: 'usebruno/bruno',
        short_name: 'Bruno',
        curator_take: 'Bruno is the cleanest Postman replacement in 2026. Collections live as plain text files in your git repo — you can diff API changes alongside code, just like everything else you ship. Native desktop app for Mac/Win/Linux, no login, no cloud sync, no rate-limited free tier. The "Postman quit being open-source" answer most teams have switched to.',
        use_this_if: 'Your team is on git and you want API collections under version control. Or Postman\'s mandatory cloud forced your hand.',
        skip_if: 'You need shared team workspaces with comments and live collaboration — Bruno is local-first only.',
        license: 'MIT',
        stars_approx: 32000,
        self_hosted: true,
      },
      {
        full_name: 'Hoppscotch/hoppscotch',
        short_name: 'Hoppscotch',
        curator_take: 'Hoppscotch is the browser-first Postman alternative. Fast, lightweight, runs at hoppscotch.io free or self-host. Supports REST, GraphQL, WebSocket, SSE in one UI. The PWA loads in <2 seconds and feels snappier than Postman ever did.',
        use_this_if: 'You want a Postman-like UX without installing anything, or you need GraphQL + WebSocket testing in the same place.',
        skip_if: 'You\'re testing flows with auth/cookies that browsers block — desktop apps like Bruno handle these cleaner.',
        license: 'MIT',
        stars_approx: 65000,
        self_hosted: true,
      },
      {
        full_name: 'httpie/cli',
        short_name: 'HTTPie',
        curator_take: 'HTTPie is the curl that humans deserve. CLI-first API testing with colored output, JSON pretty-printing, session persistence, and form-data syntax that doesn\'t require a memory of bash quoting rules. Use it in scripts, CI, and one-off debug sessions.',
        use_this_if: 'You live in the terminal and want a curl replacement that doesn\'t hate you.',
        skip_if: 'You need a GUI for managing 200+ saved requests — pair HTTPie with Bruno instead.',
        license: 'BSD-3-Clause',
        stars_approx: 35000,
        self_hosted: true,
      },
    ],
  },

  {
    slug: 'auth0',
    saas_name: 'Auth0',
    query: 'open source alternative to auth0',
    monthly_searches: 6600,
    category: 'Authentication',
    saas_blurb: 'Auth0 is the developer-friendly auth SaaS, acquired by Okta. Free tier covers 25k MAU but costs jump fast — Pro is $240/mo and Enterprise hits four figures. Self-hosting gives you the same auth flows for $0 + DB costs.',
    picks: [
      {
        full_name: 'better-auth/better-auth',
        short_name: 'Better Auth',
        curator_take: 'Better Auth is the 2026 darling for TypeScript-first teams. Drop into any Node/Bun/Deno app, supports OAuth, magic links, passkeys, multi-tenant, 2FA, organizations — out of the box. Database-agnostic (Drizzle, Prisma, Kysely all work). Adoption exploded after shadcn endorsed it.',
        use_this_if: 'You\'re on Next.js + Drizzle/Prisma and want type-safe auth that handles the modern stuff (passkeys, social, magic links) without Auth0\'s monthly bill.',
        skip_if: 'You need enterprise SSO (SAML, custom IdPs) — Better Auth has it in beta but Auth0/Ory are more mature.',
        license: 'MIT',
        stars_approx: 12000,
        self_hosted: true,
      },
      {
        full_name: 'supabase/auth',
        short_name: 'Supabase Auth',
        curator_take: 'If you\'re already on Supabase, their auth ships with the platform — JWT-based, hooks into RLS so your DB does authz, supports 20+ OAuth providers, magic links, phone OTP. Free tier covers 50k MAU, paid is $0.00325/MAU after that (~10× cheaper than Auth0).',
        use_this_if: 'Supabase is your backend, you want auth + database authz in one product, and you don\'t want to wire your own session storage.',
        skip_if: 'You\'re not on Postgres — Supabase Auth assumes you\'re using their DB.',
        license: 'Apache 2.0',
        stars_approx: 1500,
        self_hosted: true,
      },
      {
        full_name: 'ory/kratos',
        short_name: 'Ory Kratos',
        curator_take: 'Ory is the enterprise-grade open-source auth stack. Kratos handles identity, Hydra is the OAuth2 server, Keto is permissions. Each runs as its own service — more setup than Better Auth, but it\'s what you want if you need SAML, custom enterprise IdPs, or air-gapped deployments.',
        use_this_if: 'You\'re selling to enterprises that need SAML/SCIM, or you need a battle-tested OAuth2 server you control end-to-end.',
        skip_if: 'You\'re a solo dev shipping a side project — Better Auth ships in an afternoon, Ory takes a week.',
        license: 'Apache 2.0',
        stars_approx: 12000,
        self_hosted: true,
      },
    ],
  },

  {
    slug: 'stripe',
    saas_name: 'Stripe',
    query: 'open source alternative to stripe',
    monthly_searches: 5400,
    category: 'Payments',
    saas_blurb: 'Stripe is the developer-default for payments — but their fees (2.9% + 30¢ in US, 3.9%+ outside) compound at scale, and their lock-in is real. Open-source alternatives focus on metering/billing (Lago, Polar) and on routing (Hyperswitch) — they don\'t replace the actual processor, they let you switch processors.',
    picks: [
      {
        full_name: 'juspay/hyperswitch',
        short_name: 'Hyperswitch',
        curator_take: 'Hyperswitch is the open-source payment orchestrator built by JusPay (one of India\'s largest fintechs). It sits between your app and 80+ payment processors (Stripe, Razorpay, Adyen, Cybersource, etc.) so you can route, retry, and split payments without lock-in. Rust core, MIT license, used by real companies handling $1B+/year.',
        use_this_if: 'You\'re scaling past $1M/year and want to negotiate processor fees by routing volume, or you operate in multiple geos with different processor strengths.',
        skip_if: 'You\'re early-stage with one processor — adding orchestration adds latency + complexity you don\'t need yet.',
        license: 'Apache 2.0',
        stars_approx: 15000,
        self_hosted: true,
      },
      {
        full_name: 'getlago/lago',
        short_name: 'Lago',
        curator_take: 'Lago is open-source usage-based billing — the part of Stripe (Stripe Billing) that costs 0.5% per transaction plus subscription fees. Lago handles metering, plans, credits, coupons, invoicing, dunning. Pair with Stripe (or any processor) for the actual card capture; Lago owns the billing logic.',
        use_this_if: 'You\'re building usage-based or seat-based SaaS and want to control billing logic without Stripe Billing\'s cut.',
        skip_if: 'You\'re running flat-rate subscriptions only — Stripe Billing\'s included free tier is enough.',
        license: 'AGPL-3.0',
        stars_approx: 8500,
        self_hosted: true,
      },
      {
        full_name: 'polarsource/polar',
        short_name: 'Polar',
        curator_take: 'Polar is a merchant-of-record platform built for indie devs — they handle the sales tax, VAT, GST, chargebacks on your behalf, and you get one wire transfer. Lower setup friction than Stripe + Quaderno + Anrok stitched together. Open-source platform, paid hosted service (4% + 40¢, drops to 1.4% at volume).',
        use_this_if: 'You\'re selling digital goods globally and don\'t want to deal with sales tax registration across 30 jurisdictions.',
        skip_if: 'You\'re only selling to one country, or you already have an accountant handling tax compliance.',
        license: 'Apache 2.0',
        stars_approx: 4500,
        self_hosted: true,
      },
    ],
  },

  {
    slug: 'heroku',
    saas_name: 'Heroku',
    query: 'open source alternative to heroku',
    monthly_searches: 4200,
    category: 'Hosting',
    saas_blurb: 'Heroku killed its free tier in 2022 and never recovered indie-developer trust. The open-source self-hosted PaaS alternatives turn a $5 VPS into a Heroku-like git-push deploy experience — for the price of the VPS.',
    picks: [
      {
        full_name: 'coollabsio/coolify',
        short_name: 'Coolify',
        curator_take: 'Coolify is the 2026 leader for self-hosted PaaS. Beautiful UI, deploys from git, supports Docker / Nixpacks / Dockerfile, manages databases, SSL via Let\'s Encrypt, multi-server. Run on a $5 Hetzner box and host unlimited apps. The Vercel/Heroku replacement most indie devs have switched to.',
        use_this_if: 'You want git-push-to-deploy on your own hardware. Or you\'re paying $200+/month on Heroku/Vercel and want to cut that to $5.',
        skip_if: 'You don\'t want to manage a server at all — Vercel\'s free tier is still better for that.',
        license: 'Apache 2.0',
        stars_approx: 45000,
        self_hosted: true,
      },
      {
        full_name: 'dokku/dokku',
        short_name: 'Dokku',
        curator_take: 'Dokku is the OG self-hosted Heroku replacement — bash scripts on top of Docker, deploys via `git push`, plugin ecosystem for Postgres/Redis/Let\'s Encrypt. Less polished than Coolify, but it\'s been stable since 2013 and you can fully understand the entire system in an afternoon.',
        use_this_if: 'You want minimum magic — bash + Docker + git, nothing else. Or you need a Heroku replacement on a single small VPS.',
        skip_if: 'You want a GUI for managing multiple environments and team members — Coolify is the polished answer.',
        license: 'MIT',
        stars_approx: 30000,
        self_hosted: true,
      },
      {
        full_name: 'caprover/caprover',
        short_name: 'CapRover',
        curator_take: 'CapRover sits between Dokku (CLI-first) and Coolify (multi-server polish). One-click apps for WordPress / Ghost / Postgres, web-based dashboard, Docker Swarm under the hood. Good middle-ground if you want a GUI but don\'t need Coolify\'s breadth.',
        use_this_if: 'You\'re running a side project on a single VPS and want a friendly dashboard without Coolify\'s complexity.',
        skip_if: 'You\'re running production multi-region deployments — Coolify or Kamal handle that better.',
        license: 'Apache 2.0',
        stars_approx: 13000,
        self_hosted: true,
      },
    ],
  },

  {
    slug: 'loom',
    saas_name: 'Loom',
    query: 'open source alternative to loom',
    monthly_searches: 3300,
    category: 'Screen Recording',
    saas_blurb: 'Loom\'s free tier shrunk to 5-min limit and 25 videos after Atlassian acquired them. The open-source alternatives give you unlimited recordings, self-hosted sharing, and your data stays yours.',
    picks: [
      {
        full_name: 'CapSoftware/Cap',
        short_name: 'Cap',
        curator_take: 'Cap is the 2026 open-source Loom. Native Mac + Windows app, records screen + camera + audio, uploads to your own S3 / R2 / self-hosted instance, gives you a clean share link. Generous free tier on cap.so, or self-host for unlimited recordings. The Loom-killer that\'s actually delivering.',
        use_this_if: 'You record async videos daily and Loom\'s 5-min limit is killing you. Or you want your demo videos out of a SaaS that could change pricing again.',
        skip_if: 'Your team already lives in Loom\'s shared workspaces — Cap\'s team features are newer and rougher.',
        license: 'AGPL-3.0',
        stars_approx: 11000,
        self_hosted: true,
      },
      {
        full_name: 'alyssaxuu/screenity',
        short_name: 'Screenity',
        curator_take: 'Screenity is a Chrome extension that records screen + camera + mic with unlimited length, plus a tab annotation editor (draw, blur, zoom) that no other free tool offers. Records save locally; you choose where to upload. Best zero-friction recorder.',
        use_this_if: 'You need to record a quick demo with annotations + zooms and don\'t want to install a desktop app.',
        skip_if: 'You need pro-grade editing (cuts, transitions, b-roll) — use OBS + DaVinci instead.',
        license: 'GPL-3.0',
        stars_approx: 14000,
        self_hosted: true,
      },
      {
        full_name: 'obsproject/obs-studio',
        short_name: 'OBS Studio',
        curator_take: 'OBS is the streaming-grade recorder used by every Twitch streamer. Scenes, sources, transitions, multi-input audio. Steep learning curve, infinite ceiling. Free, no limits, no cloud.',
        use_this_if: 'You\'re doing tutorials, livestreams, or anything multi-source — and you\'re willing to invest a weekend learning the UI.',
        skip_if: 'You just want a 30-second walk-through link to send a teammate — Cap is 10× faster for that.',
        license: 'GPL-2.0',
        stars_approx: 64000,
        self_hosted: true,
      },
    ],
  },

  {
    slug: 'datadog',
    saas_name: 'Datadog',
    query: 'open source alternative to datadog',
    monthly_searches: 5800,
    category: 'Observability',
    saas_blurb: 'Datadog\'s pricing is the running joke of every infra engineer in 2026 — startups regularly see their Datadog bill exceed their AWS bill. The open-source alternatives give you metrics + logs + traces on a $20 VPS instead of $2,000/mo.',
    picks: [
      {
        full_name: 'grafana/grafana',
        short_name: 'Grafana + Prometheus + Loki',
        curator_take: 'The classic open-source observability triad: Prometheus collects metrics, Loki collects logs, Grafana visualizes both. Mature, well-understood, scales to billions of data points. Setup is more work than Datadog (you\'re wiring 3 services) but you fully own the data and the bill never surprises you.',
        use_this_if: 'You have a DevOps engineer or want to learn observability properly. Self-host on a $20 box for a 50-service stack.',
        skip_if: 'You want one-click setup and don\'t care about the bill — Datadog Free tier or Sentry covers small teams.',
        license: 'AGPL-3.0',
        stars_approx: 67000,
        self_hosted: true,
      },
      {
        full_name: 'SigNoz/signoz',
        short_name: 'SigNoz',
        curator_take: 'SigNoz is the modern, OpenTelemetry-native Datadog clone. One UI for metrics + logs + traces + alerts, no stitching needed. ClickHouse-backed for fast queries. Cloud free tier or self-host with Docker Compose. The closest single-pane-of-glass Datadog replacement in OSS.',
        use_this_if: 'You want Datadog\'s unified UX without Datadog\'s bill, and you can run one more Docker stack.',
        skip_if: 'You\'re tiny — Sentry (errors) + UptimeRobot (uptime) covers most early-stage needs for free.',
        license: 'MIT',
        stars_approx: 21000,
        self_hosted: true,
      },
      {
        full_name: 'openobserve/openobserve',
        short_name: 'OpenObserve',
        curator_take: 'OpenObserve is the Rust-built, S3-backed observability stack — claims 140× lower storage cost than Elasticsearch. Logs + metrics + traces, OpenTelemetry-native. Younger than SigNoz but faster on large datasets. The choice when you\'re scaling past terabytes of logs.',
        use_this_if: 'You\'re generating tons of logs and ES-based stacks (ELK) are killing your budget.',
        skip_if: 'You\'re early-stage — SigNoz or Grafana Cloud free tier is easier to start with.',
        license: 'AGPL-3.0',
        stars_approx: 14000,
        self_hosted: true,
      },
    ],
  },
];

export function getAlternativePageBySlug(slug: string): AlternativePage | undefined {
  return ALTERNATIVES.find((a) => a.slug === slug);
}

export function getAllAlternativeSlugs(): string[] {
  return ALTERNATIVES.map((a) => a.slug);
}
